"""
isiMotor-RawUDP Python Client Package
High-performance, zero-overhead telemetry & scoring reader for Le Mans Ultimate and rFactor 2.
"""

from .client import IsiMotorClient
from .decoder import (
    decode_compact_scoring,
    decode_extended_state,
    decode_force_feedback,
    decode_full_scoring,
    decode_graphics,
    decode_header,
    decode_hw_control,
    decode_packet,
    decode_system_event,
    decode_telemetry,
    decode_vehicle_scoring,
    decode_weather,
    decode_weather_control,
    encode_header,
    encode_hw_control,
    encode_weather_control,
)
from .models import (
    CompactScoring,
    ExtendedState,
    ForceFeedback,
    FullScoringSession,
    Graphics,
    HWControlCommand,
    PhysicsOptions,
    RawUdpHeader,
    SystemEvent,
    TelemInfo,
    TelemVect3,
    TelemWheel,
    VehicleScoring,
    WeatherControl,
    WeatherControlCommand,
)

__version__ = "0.1.0"
__all__ = [
    "CompactScoring",
    "ExtendedState",
    "ForceFeedback",
    "FullScoringSession",
    "Graphics",
    "HWControlCommand",
    "IsiMotorClient",
    "PhysicsOptions",
    "RawUdpHeader",
    "SystemEvent",
    "TelemInfo",
    "TelemVect3",
    "TelemWheel",
    "VehicleScoring",
    "WeatherControl",
    "WeatherControlCommand",
    "decode_compact_scoring",
    "decode_extended_state",
    "decode_force_feedback",
    "decode_full_scoring",
    "decode_graphics",
    "decode_header",
    "decode_hw_control",
    "decode_packet",
    "decode_system_event",
    "decode_telemetry",
    "decode_vehicle_scoring",
    "decode_weather",
    "decode_weather_control",
    "encode_header",
    "encode_hw_control",
    "encode_weather_control",
]
