"""
Protocol and struct layout constants for isiMotor-RawUDP-Plugin.
"""

# ── Packet Size & Struct Constants ─────────────────────────────────────────────
HEADER_SIZE = 24
HEADER_STRUCT = "<4sBBHIdBBH"
SYSTEM_EVENT_SIZE = 6
SYSTEM_EVENT_STRUCT = "<4sBB"

TELEMINFO_SIZE = 1888
COMPACT_SCORING_SIZE = 168
FULL_SCORING_SESSION_SIZE = 284
VEHICLE_SCORING_SIZE = 584

WEATHER_SIZE = 108
WEATHER_STRUCT = "<d9dddd?3x"

EXTENDED_STATE_SIZE = 68
EXTENDED_STATE_STRUCT = "<22B2x4f2d2B2xif"

FORCE_FEEDBACK_SIZE = 8
FORCE_FEEDBACK_STRUCT = "<d"

GRAPHICS_SIZE = 128
GRAPHICS_STRUCT = "<3d9d3dii"

HW_CONTROL_COMMAND_SIZE = 44
HW_CONTROL_COMMAND_STRUCT = "<32sdH2x"

WEATHER_CONTROL_COMMAND_SIZE = 64
WEATHER_CONTROL_COMMAND_STRUCT = "<8d"

# ── Packet Type IDs ────────────────────────────────────────────────────────────
PKT_TYPE_TELEMETRY = 1
PKT_TYPE_COMPACT_SCORING = 2
PKT_TYPE_SYSTEM_EVENT = 3
PKT_TYPE_FULL_SCORING = 4
PKT_TYPE_WEATHER = 7
PKT_TYPE_EXTENDED_STATE = 8
PKT_TYPE_FORCE_FEEDBACK = 9
PKT_TYPE_GRAPHICS = 10
PKT_TYPE_HW_CONTROL = 100
PKT_TYPE_WEATHER_CONTROL = 101
