# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EcuRaw(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EcuRaw()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEcuRaw(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EcuRaw
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EcuRaw
    def Tc(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # EcuRaw
    def TcMax(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # EcuRaw
    def TcCut(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # EcuRaw
    def TcCutMax(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # EcuRaw
    def TcSlip(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # EcuRaw
    def TcSlipMax(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # EcuRaw
    def AbsLevel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # EcuRaw
    def AbsMax(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # EcuRaw
    def TcActive(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # EcuRaw
    def AbsActive(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # EcuRaw
    def MotorMap(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # EcuRaw
    def MotorMapMax(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # EcuRaw
    def BrakeMigration(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # EcuRaw
    def BrakeMigrationMax(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # EcuRaw
    def FrontArb(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # EcuRaw
    def FrontArbMax(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # EcuRaw
    def RearArb(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # EcuRaw
    def RearArbMax(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # EcuRaw
    def WiperState(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # EcuRaw
    def LiftAndCoast(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def EcuRawStart(builder):
    builder.StartObject(20)

def Start(builder):
    EcuRawStart(builder)

def EcuRawAddTc(builder, tc):
    builder.PrependUint8Slot(0, tc, 0)

def AddTc(builder, tc):
    EcuRawAddTc(builder, tc)

def EcuRawAddTcMax(builder, tcMax):
    builder.PrependUint8Slot(1, tcMax, 0)

def AddTcMax(builder, tcMax):
    EcuRawAddTcMax(builder, tcMax)

def EcuRawAddTcCut(builder, tcCut):
    builder.PrependUint8Slot(2, tcCut, 0)

def AddTcCut(builder, tcCut):
    EcuRawAddTcCut(builder, tcCut)

def EcuRawAddTcCutMax(builder, tcCutMax):
    builder.PrependUint8Slot(3, tcCutMax, 0)

def AddTcCutMax(builder, tcCutMax):
    EcuRawAddTcCutMax(builder, tcCutMax)

def EcuRawAddTcSlip(builder, tcSlip):
    builder.PrependUint8Slot(4, tcSlip, 0)

def AddTcSlip(builder, tcSlip):
    EcuRawAddTcSlip(builder, tcSlip)

def EcuRawAddTcSlipMax(builder, tcSlipMax):
    builder.PrependUint8Slot(5, tcSlipMax, 0)

def AddTcSlipMax(builder, tcSlipMax):
    EcuRawAddTcSlipMax(builder, tcSlipMax)

def EcuRawAddAbsLevel(builder, absLevel):
    builder.PrependUint8Slot(6, absLevel, 0)

def AddAbsLevel(builder, absLevel):
    EcuRawAddAbsLevel(builder, absLevel)

def EcuRawAddAbsMax(builder, absMax):
    builder.PrependUint8Slot(7, absMax, 0)

def AddAbsMax(builder, absMax):
    EcuRawAddAbsMax(builder, absMax)

def EcuRawAddTcActive(builder, tcActive):
    builder.PrependUint8Slot(8, tcActive, 0)

def AddTcActive(builder, tcActive):
    EcuRawAddTcActive(builder, tcActive)

def EcuRawAddAbsActive(builder, absActive):
    builder.PrependUint8Slot(9, absActive, 0)

def AddAbsActive(builder, absActive):
    EcuRawAddAbsActive(builder, absActive)

def EcuRawAddMotorMap(builder, motorMap):
    builder.PrependUint8Slot(10, motorMap, 0)

def AddMotorMap(builder, motorMap):
    EcuRawAddMotorMap(builder, motorMap)

def EcuRawAddMotorMapMax(builder, motorMapMax):
    builder.PrependUint8Slot(11, motorMapMax, 0)

def AddMotorMapMax(builder, motorMapMax):
    EcuRawAddMotorMapMax(builder, motorMapMax)

def EcuRawAddBrakeMigration(builder, brakeMigration):
    builder.PrependUint8Slot(12, brakeMigration, 0)

def AddBrakeMigration(builder, brakeMigration):
    EcuRawAddBrakeMigration(builder, brakeMigration)

def EcuRawAddBrakeMigrationMax(builder, brakeMigrationMax):
    builder.PrependUint8Slot(13, brakeMigrationMax, 0)

def AddBrakeMigrationMax(builder, brakeMigrationMax):
    EcuRawAddBrakeMigrationMax(builder, brakeMigrationMax)

def EcuRawAddFrontArb(builder, frontArb):
    builder.PrependUint8Slot(14, frontArb, 0)

def AddFrontArb(builder, frontArb):
    EcuRawAddFrontArb(builder, frontArb)

def EcuRawAddFrontArbMax(builder, frontArbMax):
    builder.PrependUint8Slot(15, frontArbMax, 0)

def AddFrontArbMax(builder, frontArbMax):
    EcuRawAddFrontArbMax(builder, frontArbMax)

def EcuRawAddRearArb(builder, rearArb):
    builder.PrependUint8Slot(16, rearArb, 0)

def AddRearArb(builder, rearArb):
    EcuRawAddRearArb(builder, rearArb)

def EcuRawAddRearArbMax(builder, rearArbMax):
    builder.PrependUint8Slot(17, rearArbMax, 0)

def AddRearArbMax(builder, rearArbMax):
    EcuRawAddRearArbMax(builder, rearArbMax)

def EcuRawAddWiperState(builder, wiperState):
    builder.PrependUint8Slot(18, wiperState, 0)

def AddWiperState(builder, wiperState):
    EcuRawAddWiperState(builder, wiperState)

def EcuRawAddLiftAndCoast(builder, liftAndCoast):
    builder.PrependUint8Slot(19, liftAndCoast, 0)

def AddLiftAndCoast(builder, liftAndCoast):
    EcuRawAddLiftAndCoast(builder, liftAndCoast)

def EcuRawEnd(builder):
    return builder.EndObject()

def End(builder):
    return EcuRawEnd(builder)
