# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ForceFeedback(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ForceFeedback()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsForceFeedback(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ForceFeedback
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ForceFeedback
    def ForceValue(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def ForceFeedbackStart(builder):
    builder.StartObject(1)

def Start(builder):
    ForceFeedbackStart(builder)

def ForceFeedbackAddForceValue(builder, forceValue):
    builder.PrependFloat64Slot(0, forceValue, 0.0)

def AddForceValue(builder, forceValue):
    ForceFeedbackAddForceValue(builder, forceValue)

def ForceFeedbackEnd(builder):
    return builder.EndObject()

def End(builder):
    return ForceFeedbackEnd(builder)
