# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FullScoringSession(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FullScoringSession()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFullScoringSession(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FullScoringSession
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FullScoringSession
    def TrackName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FullScoringSession
    def Session(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # FullScoringSession
    def CurrentEt(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # FullScoringSession
    def EndEt(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # FullScoringSession
    def MaxLaps(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # FullScoringSession
    def TotalLapDist(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # FullScoringSession
    def NumVehicles(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # FullScoringSession
    def GamePhase(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # FullScoringSession
    def YellowFlagState(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # FullScoringSession
    def SectorFlag0(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # FullScoringSession
    def SectorFlag1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # FullScoringSession
    def SectorFlag2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # FullScoringSession
    def StartLight(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # FullScoringSession
    def NumRedLights(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # FullScoringSession
    def InRealtime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # FullScoringSession
    def PlayerName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FullScoringSession
    def PlrFileName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FullScoringSession
    def DarkCloud(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # FullScoringSession
    def Raining(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # FullScoringSession
    def AmbientTemp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # FullScoringSession
    def TrackTemp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # FullScoringSession
    def Wind(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            x = o + self._tab.Pos
            from isimotor_pulse_types.fbs_generated.isimotor.fbs.Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FullScoringSession
    def MinPathWetness(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(48))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # FullScoringSession
    def MaxPathWetness(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(50))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # FullScoringSession
    def AvgPathWetness(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # FullScoringSession
    def Lmu(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(54))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from isimotor_pulse_types.fbs_generated.isimotor.fbs.LmuScoringSession import LmuScoringSession
            obj = LmuScoringSession()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FullScoringSession
    def Vehicles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(56))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from isimotor_pulse_types.fbs_generated.isimotor.fbs.VehicleScoring import VehicleScoring
            obj = VehicleScoring()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FullScoringSession
    def VehiclesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(56))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FullScoringSession
    def VehiclesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(56))
        return o == 0

def FullScoringSessionStart(builder):
    builder.StartObject(27)

def Start(builder):
    FullScoringSessionStart(builder)

def FullScoringSessionAddTrackName(builder, trackName):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(trackName), 0)

def AddTrackName(builder, trackName):
    FullScoringSessionAddTrackName(builder, trackName)

def FullScoringSessionAddSession(builder, session):
    builder.PrependInt32Slot(1, session, 0)

def AddSession(builder, session):
    FullScoringSessionAddSession(builder, session)

def FullScoringSessionAddCurrentEt(builder, currentEt):
    builder.PrependFloat64Slot(2, currentEt, 0.0)

def AddCurrentEt(builder, currentEt):
    FullScoringSessionAddCurrentEt(builder, currentEt)

def FullScoringSessionAddEndEt(builder, endEt):
    builder.PrependFloat64Slot(3, endEt, 0.0)

def AddEndEt(builder, endEt):
    FullScoringSessionAddEndEt(builder, endEt)

def FullScoringSessionAddMaxLaps(builder, maxLaps):
    builder.PrependInt32Slot(4, maxLaps, 0)

def AddMaxLaps(builder, maxLaps):
    FullScoringSessionAddMaxLaps(builder, maxLaps)

def FullScoringSessionAddTotalLapDist(builder, totalLapDist):
    builder.PrependFloat64Slot(5, totalLapDist, 0.0)

def AddTotalLapDist(builder, totalLapDist):
    FullScoringSessionAddTotalLapDist(builder, totalLapDist)

def FullScoringSessionAddNumVehicles(builder, numVehicles):
    builder.PrependInt32Slot(6, numVehicles, 0)

def AddNumVehicles(builder, numVehicles):
    FullScoringSessionAddNumVehicles(builder, numVehicles)

def FullScoringSessionAddGamePhase(builder, gamePhase):
    builder.PrependUint8Slot(7, gamePhase, 0)

def AddGamePhase(builder, gamePhase):
    FullScoringSessionAddGamePhase(builder, gamePhase)

def FullScoringSessionAddYellowFlagState(builder, yellowFlagState):
    builder.PrependInt8Slot(8, yellowFlagState, 0)

def AddYellowFlagState(builder, yellowFlagState):
    FullScoringSessionAddYellowFlagState(builder, yellowFlagState)

def FullScoringSessionAddSectorFlag0(builder, sectorFlag0):
    builder.PrependInt8Slot(9, sectorFlag0, 0)

def AddSectorFlag0(builder, sectorFlag0):
    FullScoringSessionAddSectorFlag0(builder, sectorFlag0)

def FullScoringSessionAddSectorFlag1(builder, sectorFlag1):
    builder.PrependInt8Slot(10, sectorFlag1, 0)

def AddSectorFlag1(builder, sectorFlag1):
    FullScoringSessionAddSectorFlag1(builder, sectorFlag1)

def FullScoringSessionAddSectorFlag2(builder, sectorFlag2):
    builder.PrependInt8Slot(11, sectorFlag2, 0)

def AddSectorFlag2(builder, sectorFlag2):
    FullScoringSessionAddSectorFlag2(builder, sectorFlag2)

def FullScoringSessionAddStartLight(builder, startLight):
    builder.PrependUint8Slot(12, startLight, 0)

def AddStartLight(builder, startLight):
    FullScoringSessionAddStartLight(builder, startLight)

def FullScoringSessionAddNumRedLights(builder, numRedLights):
    builder.PrependUint8Slot(13, numRedLights, 0)

def AddNumRedLights(builder, numRedLights):
    FullScoringSessionAddNumRedLights(builder, numRedLights)

def FullScoringSessionAddInRealtime(builder, inRealtime):
    builder.PrependBoolSlot(14, inRealtime, 0)

def AddInRealtime(builder, inRealtime):
    FullScoringSessionAddInRealtime(builder, inRealtime)

def FullScoringSessionAddPlayerName(builder, playerName):
    builder.PrependUOffsetTRelativeSlot(15, flatbuffers.number_types.UOffsetTFlags.py_type(playerName), 0)

def AddPlayerName(builder, playerName):
    FullScoringSessionAddPlayerName(builder, playerName)

def FullScoringSessionAddPlrFileName(builder, plrFileName):
    builder.PrependUOffsetTRelativeSlot(16, flatbuffers.number_types.UOffsetTFlags.py_type(plrFileName), 0)

def AddPlrFileName(builder, plrFileName):
    FullScoringSessionAddPlrFileName(builder, plrFileName)

def FullScoringSessionAddDarkCloud(builder, darkCloud):
    builder.PrependFloat64Slot(17, darkCloud, 0.0)

def AddDarkCloud(builder, darkCloud):
    FullScoringSessionAddDarkCloud(builder, darkCloud)

def FullScoringSessionAddRaining(builder, raining):
    builder.PrependFloat64Slot(18, raining, 0.0)

def AddRaining(builder, raining):
    FullScoringSessionAddRaining(builder, raining)

def FullScoringSessionAddAmbientTemp(builder, ambientTemp):
    builder.PrependFloat64Slot(19, ambientTemp, 0.0)

def AddAmbientTemp(builder, ambientTemp):
    FullScoringSessionAddAmbientTemp(builder, ambientTemp)

def FullScoringSessionAddTrackTemp(builder, trackTemp):
    builder.PrependFloat64Slot(20, trackTemp, 0.0)

def AddTrackTemp(builder, trackTemp):
    FullScoringSessionAddTrackTemp(builder, trackTemp)

def FullScoringSessionAddWind(builder, wind):
    builder.PrependStructSlot(21, flatbuffers.number_types.UOffsetTFlags.py_type(wind), 0)

def AddWind(builder, wind):
    FullScoringSessionAddWind(builder, wind)

def FullScoringSessionAddMinPathWetness(builder, minPathWetness):
    builder.PrependFloat64Slot(22, minPathWetness, 0.0)

def AddMinPathWetness(builder, minPathWetness):
    FullScoringSessionAddMinPathWetness(builder, minPathWetness)

def FullScoringSessionAddMaxPathWetness(builder, maxPathWetness):
    builder.PrependFloat64Slot(23, maxPathWetness, 0.0)

def AddMaxPathWetness(builder, maxPathWetness):
    FullScoringSessionAddMaxPathWetness(builder, maxPathWetness)

def FullScoringSessionAddAvgPathWetness(builder, avgPathWetness):
    builder.PrependFloat64Slot(24, avgPathWetness, 0.0)

def AddAvgPathWetness(builder, avgPathWetness):
    FullScoringSessionAddAvgPathWetness(builder, avgPathWetness)

def FullScoringSessionAddLmu(builder, lmu):
    builder.PrependUOffsetTRelativeSlot(25, flatbuffers.number_types.UOffsetTFlags.py_type(lmu), 0)

def AddLmu(builder, lmu):
    FullScoringSessionAddLmu(builder, lmu)

def FullScoringSessionAddVehicles(builder, vehicles):
    builder.PrependUOffsetTRelativeSlot(26, flatbuffers.number_types.UOffsetTFlags.py_type(vehicles), 0)

def AddVehicles(builder, vehicles):
    FullScoringSessionAddVehicles(builder, vehicles)

def FullScoringSessionStartVehiclesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartVehiclesVector(builder, numElems: int) -> int:
    return FullScoringSessionStartVehiclesVector(builder, numElems)

def FullScoringSessionEnd(builder):
    return builder.EndObject()

def End(builder):
    return FullScoringSessionEnd(builder)
