# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class LmuScoringSession(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LmuScoringSession()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsLmuScoringSession(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # LmuScoringSession
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LmuScoringSession
    def TrackGripLevel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # LmuScoringSession
    def TrackLimitsStepsPerPoint(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # LmuScoringSession
    def TrackLimitsStepsPerPenalty(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # LmuScoringSession
    def TimeOfDaySeconds(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def LmuScoringSessionStart(builder):
    builder.StartObject(4)

def Start(builder):
    LmuScoringSessionStart(builder)

def LmuScoringSessionAddTrackGripLevel(builder, trackGripLevel):
    builder.PrependUint8Slot(0, trackGripLevel, 0)

def AddTrackGripLevel(builder, trackGripLevel):
    LmuScoringSessionAddTrackGripLevel(builder, trackGripLevel)

def LmuScoringSessionAddTrackLimitsStepsPerPoint(builder, trackLimitsStepsPerPoint):
    builder.PrependUint8Slot(1, trackLimitsStepsPerPoint, 0)

def AddTrackLimitsStepsPerPoint(builder, trackLimitsStepsPerPoint):
    LmuScoringSessionAddTrackLimitsStepsPerPoint(builder, trackLimitsStepsPerPoint)

def LmuScoringSessionAddTrackLimitsStepsPerPenalty(builder, trackLimitsStepsPerPenalty):
    builder.PrependUint8Slot(2, trackLimitsStepsPerPenalty, 0)

def AddTrackLimitsStepsPerPenalty(builder, trackLimitsStepsPerPenalty):
    LmuScoringSessionAddTrackLimitsStepsPerPenalty(builder, trackLimitsStepsPerPenalty)

def LmuScoringSessionAddTimeOfDaySeconds(builder, timeOfDaySeconds):
    builder.PrependFloat32Slot(3, timeOfDaySeconds, 0.0)

def AddTimeOfDaySeconds(builder, timeOfDaySeconds):
    LmuScoringSessionAddTimeOfDaySeconds(builder, timeOfDaySeconds)

def LmuScoringSessionEnd(builder):
    return builder.EndObject()

def End(builder):
    return LmuScoringSessionEnd(builder)
