# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class LmuVehicleScoring(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LmuVehicleScoring()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsLmuVehicleScoring(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # LmuVehicleScoring
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LmuVehicleScoring
    def FuelFraction(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # LmuVehicleScoring
    def TrackLimitsSteps(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def LmuVehicleScoringStart(builder):
    builder.StartObject(2)

def Start(builder):
    LmuVehicleScoringStart(builder)

def LmuVehicleScoringAddFuelFraction(builder, fuelFraction):
    builder.PrependFloat32Slot(0, fuelFraction, 0.0)

def AddFuelFraction(builder, fuelFraction):
    LmuVehicleScoringAddFuelFraction(builder, fuelFraction)

def LmuVehicleScoringAddTrackLimitsSteps(builder, trackLimitsSteps):
    builder.PrependUint8Slot(1, trackLimitsSteps, 0)

def AddTrackLimitsSteps(builder, trackLimitsSteps):
    LmuVehicleScoringAddTrackLimitsSteps(builder, trackLimitsSteps)

def LmuVehicleScoringEnd(builder):
    return builder.EndObject()

def End(builder):
    return LmuVehicleScoringEnd(builder)
