# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PhysicsOptions(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PhysicsOptions()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPhysicsOptions(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PhysicsOptions
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PhysicsOptions
    def TractionControl(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # PhysicsOptions
    def AntiLockBrakes(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # PhysicsOptions
    def StabilityControl(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # PhysicsOptions
    def AutoShift(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # PhysicsOptions
    def AutoClutch(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # PhysicsOptions
    def Invulnerable(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # PhysicsOptions
    def OppositeLock(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # PhysicsOptions
    def SteeringHelp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # PhysicsOptions
    def BrakingHelp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # PhysicsOptions
    def SpinRecovery(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # PhysicsOptions
    def AutoPit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # PhysicsOptions
    def AutoLift(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # PhysicsOptions
    def AutoBlip(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # PhysicsOptions
    def FuelMult(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # PhysicsOptions
    def TireMult(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # PhysicsOptions
    def MechFail(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # PhysicsOptions
    def AllowPitcrewPush(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # PhysicsOptions
    def RepeatShifts(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # PhysicsOptions
    def HoldClutch(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # PhysicsOptions
    def AutoReverse(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # PhysicsOptions
    def AlternateNeutral(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # PhysicsOptions
    def AiControl(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # PhysicsOptions
    def ManualShiftOverrideTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(48))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # PhysicsOptions
    def AutoShiftOverrideTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(50))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # PhysicsOptions
    def SpeedSensitiveSteering(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # PhysicsOptions
    def SteerRatioSpeed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(54))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def PhysicsOptionsStart(builder):
    builder.StartObject(26)

def Start(builder):
    PhysicsOptionsStart(builder)

def PhysicsOptionsAddTractionControl(builder, tractionControl):
    builder.PrependUint8Slot(0, tractionControl, 0)

def AddTractionControl(builder, tractionControl):
    PhysicsOptionsAddTractionControl(builder, tractionControl)

def PhysicsOptionsAddAntiLockBrakes(builder, antiLockBrakes):
    builder.PrependUint8Slot(1, antiLockBrakes, 0)

def AddAntiLockBrakes(builder, antiLockBrakes):
    PhysicsOptionsAddAntiLockBrakes(builder, antiLockBrakes)

def PhysicsOptionsAddStabilityControl(builder, stabilityControl):
    builder.PrependUint8Slot(2, stabilityControl, 0)

def AddStabilityControl(builder, stabilityControl):
    PhysicsOptionsAddStabilityControl(builder, stabilityControl)

def PhysicsOptionsAddAutoShift(builder, autoShift):
    builder.PrependUint8Slot(3, autoShift, 0)

def AddAutoShift(builder, autoShift):
    PhysicsOptionsAddAutoShift(builder, autoShift)

def PhysicsOptionsAddAutoClutch(builder, autoClutch):
    builder.PrependUint8Slot(4, autoClutch, 0)

def AddAutoClutch(builder, autoClutch):
    PhysicsOptionsAddAutoClutch(builder, autoClutch)

def PhysicsOptionsAddInvulnerable(builder, invulnerable):
    builder.PrependUint8Slot(5, invulnerable, 0)

def AddInvulnerable(builder, invulnerable):
    PhysicsOptionsAddInvulnerable(builder, invulnerable)

def PhysicsOptionsAddOppositeLock(builder, oppositeLock):
    builder.PrependUint8Slot(6, oppositeLock, 0)

def AddOppositeLock(builder, oppositeLock):
    PhysicsOptionsAddOppositeLock(builder, oppositeLock)

def PhysicsOptionsAddSteeringHelp(builder, steeringHelp):
    builder.PrependUint8Slot(7, steeringHelp, 0)

def AddSteeringHelp(builder, steeringHelp):
    PhysicsOptionsAddSteeringHelp(builder, steeringHelp)

def PhysicsOptionsAddBrakingHelp(builder, brakingHelp):
    builder.PrependUint8Slot(8, brakingHelp, 0)

def AddBrakingHelp(builder, brakingHelp):
    PhysicsOptionsAddBrakingHelp(builder, brakingHelp)

def PhysicsOptionsAddSpinRecovery(builder, spinRecovery):
    builder.PrependUint8Slot(9, spinRecovery, 0)

def AddSpinRecovery(builder, spinRecovery):
    PhysicsOptionsAddSpinRecovery(builder, spinRecovery)

def PhysicsOptionsAddAutoPit(builder, autoPit):
    builder.PrependUint8Slot(10, autoPit, 0)

def AddAutoPit(builder, autoPit):
    PhysicsOptionsAddAutoPit(builder, autoPit)

def PhysicsOptionsAddAutoLift(builder, autoLift):
    builder.PrependUint8Slot(11, autoLift, 0)

def AddAutoLift(builder, autoLift):
    PhysicsOptionsAddAutoLift(builder, autoLift)

def PhysicsOptionsAddAutoBlip(builder, autoBlip):
    builder.PrependUint8Slot(12, autoBlip, 0)

def AddAutoBlip(builder, autoBlip):
    PhysicsOptionsAddAutoBlip(builder, autoBlip)

def PhysicsOptionsAddFuelMult(builder, fuelMult):
    builder.PrependUint8Slot(13, fuelMult, 0)

def AddFuelMult(builder, fuelMult):
    PhysicsOptionsAddFuelMult(builder, fuelMult)

def PhysicsOptionsAddTireMult(builder, tireMult):
    builder.PrependUint8Slot(14, tireMult, 0)

def AddTireMult(builder, tireMult):
    PhysicsOptionsAddTireMult(builder, tireMult)

def PhysicsOptionsAddMechFail(builder, mechFail):
    builder.PrependUint8Slot(15, mechFail, 0)

def AddMechFail(builder, mechFail):
    PhysicsOptionsAddMechFail(builder, mechFail)

def PhysicsOptionsAddAllowPitcrewPush(builder, allowPitcrewPush):
    builder.PrependUint8Slot(16, allowPitcrewPush, 0)

def AddAllowPitcrewPush(builder, allowPitcrewPush):
    PhysicsOptionsAddAllowPitcrewPush(builder, allowPitcrewPush)

def PhysicsOptionsAddRepeatShifts(builder, repeatShifts):
    builder.PrependUint8Slot(17, repeatShifts, 0)

def AddRepeatShifts(builder, repeatShifts):
    PhysicsOptionsAddRepeatShifts(builder, repeatShifts)

def PhysicsOptionsAddHoldClutch(builder, holdClutch):
    builder.PrependUint8Slot(18, holdClutch, 0)

def AddHoldClutch(builder, holdClutch):
    PhysicsOptionsAddHoldClutch(builder, holdClutch)

def PhysicsOptionsAddAutoReverse(builder, autoReverse):
    builder.PrependUint8Slot(19, autoReverse, 0)

def AddAutoReverse(builder, autoReverse):
    PhysicsOptionsAddAutoReverse(builder, autoReverse)

def PhysicsOptionsAddAlternateNeutral(builder, alternateNeutral):
    builder.PrependUint8Slot(20, alternateNeutral, 0)

def AddAlternateNeutral(builder, alternateNeutral):
    PhysicsOptionsAddAlternateNeutral(builder, alternateNeutral)

def PhysicsOptionsAddAiControl(builder, aiControl):
    builder.PrependUint8Slot(21, aiControl, 0)

def AddAiControl(builder, aiControl):
    PhysicsOptionsAddAiControl(builder, aiControl)

def PhysicsOptionsAddManualShiftOverrideTime(builder, manualShiftOverrideTime):
    builder.PrependFloat32Slot(22, manualShiftOverrideTime, 0.0)

def AddManualShiftOverrideTime(builder, manualShiftOverrideTime):
    PhysicsOptionsAddManualShiftOverrideTime(builder, manualShiftOverrideTime)

def PhysicsOptionsAddAutoShiftOverrideTime(builder, autoShiftOverrideTime):
    builder.PrependFloat32Slot(23, autoShiftOverrideTime, 0.0)

def AddAutoShiftOverrideTime(builder, autoShiftOverrideTime):
    PhysicsOptionsAddAutoShiftOverrideTime(builder, autoShiftOverrideTime)

def PhysicsOptionsAddSpeedSensitiveSteering(builder, speedSensitiveSteering):
    builder.PrependFloat32Slot(24, speedSensitiveSteering, 0.0)

def AddSpeedSensitiveSteering(builder, speedSensitiveSteering):
    PhysicsOptionsAddSpeedSensitiveSteering(builder, speedSensitiveSteering)

def PhysicsOptionsAddSteerRatioSpeed(builder, steerRatioSpeed):
    builder.PrependFloat32Slot(25, steerRatioSpeed, 0.0)

def AddSteerRatioSpeed(builder, steerRatioSpeed):
    PhysicsOptionsAddSteerRatioSpeed(builder, steerRatioSpeed)

def PhysicsOptionsEnd(builder):
    return builder.EndObject()

def End(builder):
    return PhysicsOptionsEnd(builder)
