# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WeatherControl(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WeatherControl()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWeatherControl(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WeatherControl
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WeatherControl
    def Et(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # WeatherControl
    def Raining(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # WeatherControl
    def RainingAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float64Flags, o)
        return 0

    # WeatherControl
    def RainingLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # WeatherControl
    def RainingIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # WeatherControl
    def Cloudiness(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # WeatherControl
    def AmbientTempK(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # WeatherControl
    def WindMaxSpeed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # WeatherControl
    def ApplyCloudinessInstantly(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def WeatherControlStart(builder):
    builder.StartObject(6)

def Start(builder):
    WeatherControlStart(builder)

def WeatherControlAddEt(builder, et):
    builder.PrependFloat64Slot(0, et, 0.0)

def AddEt(builder, et):
    WeatherControlAddEt(builder, et)

def WeatherControlAddRaining(builder, raining):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(raining), 0)

def AddRaining(builder, raining):
    WeatherControlAddRaining(builder, raining)

def WeatherControlStartRainingVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def StartRainingVector(builder, numElems: int) -> int:
    return WeatherControlStartRainingVector(builder, numElems)

def WeatherControlAddCloudiness(builder, cloudiness):
    builder.PrependFloat64Slot(2, cloudiness, 0.0)

def AddCloudiness(builder, cloudiness):
    WeatherControlAddCloudiness(builder, cloudiness)

def WeatherControlAddAmbientTempK(builder, ambientTempK):
    builder.PrependFloat64Slot(3, ambientTempK, 0.0)

def AddAmbientTempK(builder, ambientTempK):
    WeatherControlAddAmbientTempK(builder, ambientTempK)

def WeatherControlAddWindMaxSpeed(builder, windMaxSpeed):
    builder.PrependFloat64Slot(4, windMaxSpeed, 0.0)

def AddWindMaxSpeed(builder, windMaxSpeed):
    WeatherControlAddWindMaxSpeed(builder, windMaxSpeed)

def WeatherControlAddApplyCloudinessInstantly(builder, applyCloudinessInstantly):
    builder.PrependBoolSlot(5, applyCloudinessInstantly, 0)

def AddApplyCloudinessInstantly(builder, applyCloudinessInstantly):
    WeatherControlAddApplyCloudinessInstantly(builder, applyCloudinessInstantly)

def WeatherControlEnd(builder):
    return builder.EndObject()

def End(builder):
    return WeatherControlEnd(builder)
