# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ExtendedState(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ExtendedState()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsExtendedState(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ExtendedState
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ExtendedState
    def Physics(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from isimotor_rawudp_types.fbs_generated.isimotor.fbs.PhysicsOptions import PhysicsOptions
            obj = PhysicsOptions()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ExtendedState
    def MaxImpactMagnitude(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # ExtendedState
    def AccumulatedImpactMagnitude(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # ExtendedState
    def InRealtimeFc(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ExtendedState
    def SessionStarted(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ExtendedState
    def Session(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ExtendedState
    def CurrentPitSpeedLimit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def ExtendedStateStart(builder):
    builder.StartObject(7)

def Start(builder):
    ExtendedStateStart(builder)

def ExtendedStateAddPhysics(builder, physics):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(physics), 0)

def AddPhysics(builder, physics):
    ExtendedStateAddPhysics(builder, physics)

def ExtendedStateAddMaxImpactMagnitude(builder, maxImpactMagnitude):
    builder.PrependFloat64Slot(1, maxImpactMagnitude, 0.0)

def AddMaxImpactMagnitude(builder, maxImpactMagnitude):
    ExtendedStateAddMaxImpactMagnitude(builder, maxImpactMagnitude)

def ExtendedStateAddAccumulatedImpactMagnitude(builder, accumulatedImpactMagnitude):
    builder.PrependFloat64Slot(2, accumulatedImpactMagnitude, 0.0)

def AddAccumulatedImpactMagnitude(builder, accumulatedImpactMagnitude):
    ExtendedStateAddAccumulatedImpactMagnitude(builder, accumulatedImpactMagnitude)

def ExtendedStateAddInRealtimeFc(builder, inRealtimeFc):
    builder.PrependBoolSlot(3, inRealtimeFc, 0)

def AddInRealtimeFc(builder, inRealtimeFc):
    ExtendedStateAddInRealtimeFc(builder, inRealtimeFc)

def ExtendedStateAddSessionStarted(builder, sessionStarted):
    builder.PrependBoolSlot(4, sessionStarted, 0)

def AddSessionStarted(builder, sessionStarted):
    ExtendedStateAddSessionStarted(builder, sessionStarted)

def ExtendedStateAddSession(builder, session):
    builder.PrependInt32Slot(5, session, 0)

def AddSession(builder, session):
    ExtendedStateAddSession(builder, session)

def ExtendedStateAddCurrentPitSpeedLimit(builder, currentPitSpeedLimit):
    builder.PrependFloat32Slot(6, currentPitSpeedLimit, 0.0)

def AddCurrentPitSpeedLimit(builder, currentPitSpeedLimit):
    ExtendedStateAddCurrentPitSpeedLimit(builder, currentPitSpeedLimit)

def ExtendedStateEnd(builder):
    return builder.EndObject()

def End(builder):
    return ExtendedStateEnd(builder)
