# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Graphics(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Graphics()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGraphics(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Graphics
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Graphics
    def CamPos(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from isimotor_rawudp_types.fbs_generated.isimotor.fbs.Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Graphics
    def CamOri0(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from isimotor_rawudp_types.fbs_generated.isimotor.fbs.Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Graphics
    def CamOri1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from isimotor_rawudp_types.fbs_generated.isimotor.fbs.Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Graphics
    def CamOri2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            from isimotor_rawudp_types.fbs_generated.isimotor.fbs.Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Graphics
    def AmbientRed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Graphics
    def AmbientGreen(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Graphics
    def AmbientBlue(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Graphics
    def SlotId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Graphics
    def CameraType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def GraphicsStart(builder):
    builder.StartObject(9)

def Start(builder):
    GraphicsStart(builder)

def GraphicsAddCamPos(builder, camPos):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(camPos), 0)

def AddCamPos(builder, camPos):
    GraphicsAddCamPos(builder, camPos)

def GraphicsAddCamOri0(builder, camOri0):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(camOri0), 0)

def AddCamOri0(builder, camOri0):
    GraphicsAddCamOri0(builder, camOri0)

def GraphicsAddCamOri1(builder, camOri1):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(camOri1), 0)

def AddCamOri1(builder, camOri1):
    GraphicsAddCamOri1(builder, camOri1)

def GraphicsAddCamOri2(builder, camOri2):
    builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(camOri2), 0)

def AddCamOri2(builder, camOri2):
    GraphicsAddCamOri2(builder, camOri2)

def GraphicsAddAmbientRed(builder, ambientRed):
    builder.PrependFloat64Slot(4, ambientRed, 0.0)

def AddAmbientRed(builder, ambientRed):
    GraphicsAddAmbientRed(builder, ambientRed)

def GraphicsAddAmbientGreen(builder, ambientGreen):
    builder.PrependFloat64Slot(5, ambientGreen, 0.0)

def AddAmbientGreen(builder, ambientGreen):
    GraphicsAddAmbientGreen(builder, ambientGreen)

def GraphicsAddAmbientBlue(builder, ambientBlue):
    builder.PrependFloat64Slot(6, ambientBlue, 0.0)

def AddAmbientBlue(builder, ambientBlue):
    GraphicsAddAmbientBlue(builder, ambientBlue)

def GraphicsAddSlotId(builder, slotId):
    builder.PrependInt32Slot(7, slotId, 0)

def AddSlotId(builder, slotId):
    GraphicsAddSlotId(builder, slotId)

def GraphicsAddCameraType(builder, cameraType):
    builder.PrependInt32Slot(8, cameraType, 0)

def AddCameraType(builder, cameraType):
    GraphicsAddCameraType(builder, cameraType)

def GraphicsEnd(builder):
    return builder.EndObject()

def End(builder):
    return GraphicsEnd(builder)
