# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class LmuTelemetry(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LmuTelemetry()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsLmuTelemetry(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # LmuTelemetry
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LmuTelemetry
    def Ecu(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from isimotor_rawudp_types.fbs_generated.isimotor.fbs.EcuRaw import EcuRaw
            obj = EcuRaw()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # LmuTelemetry
    def VirtualEnergy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # LmuTelemetry
    def RegenKw(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # LmuTelemetry
    def TrackLimitsSteps(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # LmuTelemetry
    def VehicleModel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def LmuTelemetryStart(builder):
    builder.StartObject(5)

def Start(builder):
    LmuTelemetryStart(builder)

def LmuTelemetryAddEcu(builder, ecu):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(ecu), 0)

def AddEcu(builder, ecu):
    LmuTelemetryAddEcu(builder, ecu)

def LmuTelemetryAddVirtualEnergy(builder, virtualEnergy):
    builder.PrependFloat64Slot(1, virtualEnergy, 0.0)

def AddVirtualEnergy(builder, virtualEnergy):
    LmuTelemetryAddVirtualEnergy(builder, virtualEnergy)

def LmuTelemetryAddRegenKw(builder, regenKw):
    builder.PrependFloat64Slot(2, regenKw, 0.0)

def AddRegenKw(builder, regenKw):
    LmuTelemetryAddRegenKw(builder, regenKw)

def LmuTelemetryAddTrackLimitsSteps(builder, trackLimitsSteps):
    builder.PrependUint8Slot(3, trackLimitsSteps, 0)

def AddTrackLimitsSteps(builder, trackLimitsSteps):
    LmuTelemetryAddTrackLimitsSteps(builder, trackLimitsSteps)

def LmuTelemetryAddVehicleModel(builder, vehicleModel):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(vehicleModel), 0)

def AddVehicleModel(builder, vehicleModel):
    LmuTelemetryAddVehicleModel(builder, vehicleModel)

def LmuTelemetryEnd(builder):
    return builder.EndObject()

def End(builder):
    return LmuTelemetryEnd(builder)
