# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class LmuWheel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LmuWheel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsLmuWheel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # LmuWheel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LmuWheel
    def CompoundType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # LmuWheel
    def BrakeWearMeters(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def LmuWheelStart(builder):
    builder.StartObject(2)

def Start(builder):
    LmuWheelStart(builder)

def LmuWheelAddCompoundType(builder, compoundType):
    builder.PrependUint8Slot(0, compoundType, 0)

def AddCompoundType(builder, compoundType):
    LmuWheelAddCompoundType(builder, compoundType)

def LmuWheelAddBrakeWearMeters(builder, brakeWearMeters):
    builder.PrependFloat64Slot(1, brakeWearMeters, 0.0)

def AddBrakeWearMeters(builder, brakeWearMeters):
    LmuWheelAddBrakeWearMeters(builder, brakeWearMeters)

def LmuWheelEnd(builder):
    return builder.EndObject()

def End(builder):
    return LmuWheelEnd(builder)
