# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TelemInfo(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TelemInfo()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTelemInfo(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TelemInfo
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TelemInfo
    def SlotId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # TelemInfo
    def DeltaTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemInfo
    def ElapsedTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemInfo
    def LapNumber(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # TelemInfo
    def LapStartEt(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemInfo
    def VehicleName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # TelemInfo
    def TrackName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # TelemInfo
    def Pos(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = o + self._tab.Pos
            from isimotor_rawudp_types.fbs_generated.isimotor.fbs.Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TelemInfo
    def LocalVel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = o + self._tab.Pos
            from isimotor_rawudp_types.fbs_generated.isimotor.fbs.Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TelemInfo
    def LocalAccel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            x = o + self._tab.Pos
            from isimotor_rawudp_types.fbs_generated.isimotor.fbs.Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TelemInfo
    def Ori0(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            x = o + self._tab.Pos
            from isimotor_rawudp_types.fbs_generated.isimotor.fbs.Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TelemInfo
    def Ori1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            x = o + self._tab.Pos
            from isimotor_rawudp_types.fbs_generated.isimotor.fbs.Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TelemInfo
    def Ori2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            x = o + self._tab.Pos
            from isimotor_rawudp_types.fbs_generated.isimotor.fbs.Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TelemInfo
    def LocalRot(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            x = o + self._tab.Pos
            from isimotor_rawudp_types.fbs_generated.isimotor.fbs.Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TelemInfo
    def LocalRotAccel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            x = o + self._tab.Pos
            from isimotor_rawudp_types.fbs_generated.isimotor.fbs.Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TelemInfo
    def Gear(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # TelemInfo
    def EngineRpm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemInfo
    def EngineWaterTemp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemInfo
    def EngineOilTemp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemInfo
    def ClutchRpm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemInfo
    def UnfilteredThrottle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemInfo
    def UnfilteredBrake(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemInfo
    def UnfilteredSteering(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(48))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemInfo
    def UnfilteredClutch(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(50))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemInfo
    def FilteredThrottle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemInfo
    def FilteredBrake(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(54))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemInfo
    def FilteredSteering(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(56))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemInfo
    def FilteredClutch(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(58))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemInfo
    def SteeringShaftTorque(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(60))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemInfo
    def Front3rdDeflection(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(62))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemInfo
    def Rear3rdDeflection(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(64))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemInfo
    def FrontWingHeight(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(66))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemInfo
    def FrontRideHeight(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(68))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemInfo
    def RearRideHeight(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(70))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemInfo
    def Drag(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(72))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemInfo
    def FrontDownforce(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(74))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemInfo
    def RearDownforce(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(76))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemInfo
    def Fuel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(78))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemInfo
    def EngineMaxRpm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(80))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemInfo
    def ScheduledStops(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(82))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # TelemInfo
    def Overheating(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(84))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # TelemInfo
    def Detached(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(86))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # TelemInfo
    def Headlights(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(88))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # TelemInfo
    def DentSeverity(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(90))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # TelemInfo
    def DentSeverityAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(90))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # TelemInfo
    def DentSeverityLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(90))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TelemInfo
    def DentSeverityIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(90))
        return o == 0

    # TelemInfo
    def LastImpactEt(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(92))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemInfo
    def LastImpactMagnitude(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(94))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemInfo
    def LastImpactPos(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(96))
        if o != 0:
            x = o + self._tab.Pos
            from isimotor_rawudp_types.fbs_generated.isimotor.fbs.Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TelemInfo
    def EngineTorque(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(98))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemInfo
    def CurrentSector(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(100))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # TelemInfo
    def SpeedLimiter(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(102))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # TelemInfo
    def MaxGears(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(104))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # TelemInfo
    def FrontTireCompoundIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(106))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # TelemInfo
    def RearTireCompoundIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(108))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # TelemInfo
    def FuelCapacity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(110))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemInfo
    def FrontFlapActivated(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(112))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # TelemInfo
    def RearFlapActivated(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(114))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # TelemInfo
    def RearFlapLegalStatus(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(116))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # TelemInfo
    def IgnitionStarter(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(118))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # TelemInfo
    def FrontTireCompoundName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(120))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # TelemInfo
    def RearTireCompoundName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(122))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # TelemInfo
    def SpeedLimiterAvailable(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(124))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # TelemInfo
    def AntiStallActivated(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(126))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # TelemInfo
    def VisualSteeringWheelRange(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(128))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # TelemInfo
    def RearBrakeBias(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(130))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemInfo
    def TurboBoostPressure(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(132))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemInfo
    def PhysicsToGraphicsOffset(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(134))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # TelemInfo
    def PhysicsToGraphicsOffsetAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(134))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # TelemInfo
    def PhysicsToGraphicsOffsetLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(134))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TelemInfo
    def PhysicsToGraphicsOffsetIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(134))
        return o == 0

    # TelemInfo
    def PhysicalSteeringWheelRange(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(136))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # TelemInfo
    def BatteryChargeFraction(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(138))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemInfo
    def ElectricBoostMotorTorque(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(140))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemInfo
    def ElectricBoostMotorRpm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(142))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemInfo
    def ElectricBoostMotorTemperature(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(144))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemInfo
    def ElectricBoostWaterTemperature(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(146))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemInfo
    def ElectricBoostMotorState(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(148))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # TelemInfo
    def Lmu(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(150))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from isimotor_rawudp_types.fbs_generated.isimotor.fbs.LmuTelemetry import LmuTelemetry
            obj = LmuTelemetry()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TelemInfo
    def Wheels(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(152))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from isimotor_rawudp_types.fbs_generated.isimotor.fbs.TelemWheel import TelemWheel
            obj = TelemWheel()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TelemInfo
    def WheelsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(152))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TelemInfo
    def WheelsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(152))
        return o == 0

def TelemInfoStart(builder):
    builder.StartObject(75)

def Start(builder):
    TelemInfoStart(builder)

def TelemInfoAddSlotId(builder, slotId):
    builder.PrependInt32Slot(0, slotId, 0)

def AddSlotId(builder, slotId):
    TelemInfoAddSlotId(builder, slotId)

def TelemInfoAddDeltaTime(builder, deltaTime):
    builder.PrependFloat64Slot(1, deltaTime, 0.0)

def AddDeltaTime(builder, deltaTime):
    TelemInfoAddDeltaTime(builder, deltaTime)

def TelemInfoAddElapsedTime(builder, elapsedTime):
    builder.PrependFloat64Slot(2, elapsedTime, 0.0)

def AddElapsedTime(builder, elapsedTime):
    TelemInfoAddElapsedTime(builder, elapsedTime)

def TelemInfoAddLapNumber(builder, lapNumber):
    builder.PrependInt32Slot(3, lapNumber, 0)

def AddLapNumber(builder, lapNumber):
    TelemInfoAddLapNumber(builder, lapNumber)

def TelemInfoAddLapStartEt(builder, lapStartEt):
    builder.PrependFloat64Slot(4, lapStartEt, 0.0)

def AddLapStartEt(builder, lapStartEt):
    TelemInfoAddLapStartEt(builder, lapStartEt)

def TelemInfoAddVehicleName(builder, vehicleName):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(vehicleName), 0)

def AddVehicleName(builder, vehicleName):
    TelemInfoAddVehicleName(builder, vehicleName)

def TelemInfoAddTrackName(builder, trackName):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(trackName), 0)

def AddTrackName(builder, trackName):
    TelemInfoAddTrackName(builder, trackName)

def TelemInfoAddPos(builder, pos):
    builder.PrependStructSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(pos), 0)

def AddPos(builder, pos):
    TelemInfoAddPos(builder, pos)

def TelemInfoAddLocalVel(builder, localVel):
    builder.PrependStructSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(localVel), 0)

def AddLocalVel(builder, localVel):
    TelemInfoAddLocalVel(builder, localVel)

def TelemInfoAddLocalAccel(builder, localAccel):
    builder.PrependStructSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(localAccel), 0)

def AddLocalAccel(builder, localAccel):
    TelemInfoAddLocalAccel(builder, localAccel)

def TelemInfoAddOri0(builder, ori0):
    builder.PrependStructSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(ori0), 0)

def AddOri0(builder, ori0):
    TelemInfoAddOri0(builder, ori0)

def TelemInfoAddOri1(builder, ori1):
    builder.PrependStructSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(ori1), 0)

def AddOri1(builder, ori1):
    TelemInfoAddOri1(builder, ori1)

def TelemInfoAddOri2(builder, ori2):
    builder.PrependStructSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(ori2), 0)

def AddOri2(builder, ori2):
    TelemInfoAddOri2(builder, ori2)

def TelemInfoAddLocalRot(builder, localRot):
    builder.PrependStructSlot(13, flatbuffers.number_types.UOffsetTFlags.py_type(localRot), 0)

def AddLocalRot(builder, localRot):
    TelemInfoAddLocalRot(builder, localRot)

def TelemInfoAddLocalRotAccel(builder, localRotAccel):
    builder.PrependStructSlot(14, flatbuffers.number_types.UOffsetTFlags.py_type(localRotAccel), 0)

def AddLocalRotAccel(builder, localRotAccel):
    TelemInfoAddLocalRotAccel(builder, localRotAccel)

def TelemInfoAddGear(builder, gear):
    builder.PrependInt32Slot(15, gear, 0)

def AddGear(builder, gear):
    TelemInfoAddGear(builder, gear)

def TelemInfoAddEngineRpm(builder, engineRpm):
    builder.PrependFloat64Slot(16, engineRpm, 0.0)

def AddEngineRpm(builder, engineRpm):
    TelemInfoAddEngineRpm(builder, engineRpm)

def TelemInfoAddEngineWaterTemp(builder, engineWaterTemp):
    builder.PrependFloat64Slot(17, engineWaterTemp, 0.0)

def AddEngineWaterTemp(builder, engineWaterTemp):
    TelemInfoAddEngineWaterTemp(builder, engineWaterTemp)

def TelemInfoAddEngineOilTemp(builder, engineOilTemp):
    builder.PrependFloat64Slot(18, engineOilTemp, 0.0)

def AddEngineOilTemp(builder, engineOilTemp):
    TelemInfoAddEngineOilTemp(builder, engineOilTemp)

def TelemInfoAddClutchRpm(builder, clutchRpm):
    builder.PrependFloat64Slot(19, clutchRpm, 0.0)

def AddClutchRpm(builder, clutchRpm):
    TelemInfoAddClutchRpm(builder, clutchRpm)

def TelemInfoAddUnfilteredThrottle(builder, unfilteredThrottle):
    builder.PrependFloat64Slot(20, unfilteredThrottle, 0.0)

def AddUnfilteredThrottle(builder, unfilteredThrottle):
    TelemInfoAddUnfilteredThrottle(builder, unfilteredThrottle)

def TelemInfoAddUnfilteredBrake(builder, unfilteredBrake):
    builder.PrependFloat64Slot(21, unfilteredBrake, 0.0)

def AddUnfilteredBrake(builder, unfilteredBrake):
    TelemInfoAddUnfilteredBrake(builder, unfilteredBrake)

def TelemInfoAddUnfilteredSteering(builder, unfilteredSteering):
    builder.PrependFloat64Slot(22, unfilteredSteering, 0.0)

def AddUnfilteredSteering(builder, unfilteredSteering):
    TelemInfoAddUnfilteredSteering(builder, unfilteredSteering)

def TelemInfoAddUnfilteredClutch(builder, unfilteredClutch):
    builder.PrependFloat64Slot(23, unfilteredClutch, 0.0)

def AddUnfilteredClutch(builder, unfilteredClutch):
    TelemInfoAddUnfilteredClutch(builder, unfilteredClutch)

def TelemInfoAddFilteredThrottle(builder, filteredThrottle):
    builder.PrependFloat64Slot(24, filteredThrottle, 0.0)

def AddFilteredThrottle(builder, filteredThrottle):
    TelemInfoAddFilteredThrottle(builder, filteredThrottle)

def TelemInfoAddFilteredBrake(builder, filteredBrake):
    builder.PrependFloat64Slot(25, filteredBrake, 0.0)

def AddFilteredBrake(builder, filteredBrake):
    TelemInfoAddFilteredBrake(builder, filteredBrake)

def TelemInfoAddFilteredSteering(builder, filteredSteering):
    builder.PrependFloat64Slot(26, filteredSteering, 0.0)

def AddFilteredSteering(builder, filteredSteering):
    TelemInfoAddFilteredSteering(builder, filteredSteering)

def TelemInfoAddFilteredClutch(builder, filteredClutch):
    builder.PrependFloat64Slot(27, filteredClutch, 0.0)

def AddFilteredClutch(builder, filteredClutch):
    TelemInfoAddFilteredClutch(builder, filteredClutch)

def TelemInfoAddSteeringShaftTorque(builder, steeringShaftTorque):
    builder.PrependFloat64Slot(28, steeringShaftTorque, 0.0)

def AddSteeringShaftTorque(builder, steeringShaftTorque):
    TelemInfoAddSteeringShaftTorque(builder, steeringShaftTorque)

def TelemInfoAddFront3rdDeflection(builder, front3rdDeflection):
    builder.PrependFloat64Slot(29, front3rdDeflection, 0.0)

def AddFront3rdDeflection(builder, front3rdDeflection):
    TelemInfoAddFront3rdDeflection(builder, front3rdDeflection)

def TelemInfoAddRear3rdDeflection(builder, rear3rdDeflection):
    builder.PrependFloat64Slot(30, rear3rdDeflection, 0.0)

def AddRear3rdDeflection(builder, rear3rdDeflection):
    TelemInfoAddRear3rdDeflection(builder, rear3rdDeflection)

def TelemInfoAddFrontWingHeight(builder, frontWingHeight):
    builder.PrependFloat64Slot(31, frontWingHeight, 0.0)

def AddFrontWingHeight(builder, frontWingHeight):
    TelemInfoAddFrontWingHeight(builder, frontWingHeight)

def TelemInfoAddFrontRideHeight(builder, frontRideHeight):
    builder.PrependFloat64Slot(32, frontRideHeight, 0.0)

def AddFrontRideHeight(builder, frontRideHeight):
    TelemInfoAddFrontRideHeight(builder, frontRideHeight)

def TelemInfoAddRearRideHeight(builder, rearRideHeight):
    builder.PrependFloat64Slot(33, rearRideHeight, 0.0)

def AddRearRideHeight(builder, rearRideHeight):
    TelemInfoAddRearRideHeight(builder, rearRideHeight)

def TelemInfoAddDrag(builder, drag):
    builder.PrependFloat64Slot(34, drag, 0.0)

def AddDrag(builder, drag):
    TelemInfoAddDrag(builder, drag)

def TelemInfoAddFrontDownforce(builder, frontDownforce):
    builder.PrependFloat64Slot(35, frontDownforce, 0.0)

def AddFrontDownforce(builder, frontDownforce):
    TelemInfoAddFrontDownforce(builder, frontDownforce)

def TelemInfoAddRearDownforce(builder, rearDownforce):
    builder.PrependFloat64Slot(36, rearDownforce, 0.0)

def AddRearDownforce(builder, rearDownforce):
    TelemInfoAddRearDownforce(builder, rearDownforce)

def TelemInfoAddFuel(builder, fuel):
    builder.PrependFloat64Slot(37, fuel, 0.0)

def AddFuel(builder, fuel):
    TelemInfoAddFuel(builder, fuel)

def TelemInfoAddEngineMaxRpm(builder, engineMaxRpm):
    builder.PrependFloat64Slot(38, engineMaxRpm, 0.0)

def AddEngineMaxRpm(builder, engineMaxRpm):
    TelemInfoAddEngineMaxRpm(builder, engineMaxRpm)

def TelemInfoAddScheduledStops(builder, scheduledStops):
    builder.PrependUint8Slot(39, scheduledStops, 0)

def AddScheduledStops(builder, scheduledStops):
    TelemInfoAddScheduledStops(builder, scheduledStops)

def TelemInfoAddOverheating(builder, overheating):
    builder.PrependBoolSlot(40, overheating, 0)

def AddOverheating(builder, overheating):
    TelemInfoAddOverheating(builder, overheating)

def TelemInfoAddDetached(builder, detached):
    builder.PrependBoolSlot(41, detached, 0)

def AddDetached(builder, detached):
    TelemInfoAddDetached(builder, detached)

def TelemInfoAddHeadlights(builder, headlights):
    builder.PrependBoolSlot(42, headlights, 0)

def AddHeadlights(builder, headlights):
    TelemInfoAddHeadlights(builder, headlights)

def TelemInfoAddDentSeverity(builder, dentSeverity):
    builder.PrependUOffsetTRelativeSlot(43, flatbuffers.number_types.UOffsetTFlags.py_type(dentSeverity), 0)

def AddDentSeverity(builder, dentSeverity):
    TelemInfoAddDentSeverity(builder, dentSeverity)

def TelemInfoStartDentSeverityVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartDentSeverityVector(builder, numElems: int) -> int:
    return TelemInfoStartDentSeverityVector(builder, numElems)

def TelemInfoAddLastImpactEt(builder, lastImpactEt):
    builder.PrependFloat64Slot(44, lastImpactEt, 0.0)

def AddLastImpactEt(builder, lastImpactEt):
    TelemInfoAddLastImpactEt(builder, lastImpactEt)

def TelemInfoAddLastImpactMagnitude(builder, lastImpactMagnitude):
    builder.PrependFloat64Slot(45, lastImpactMagnitude, 0.0)

def AddLastImpactMagnitude(builder, lastImpactMagnitude):
    TelemInfoAddLastImpactMagnitude(builder, lastImpactMagnitude)

def TelemInfoAddLastImpactPos(builder, lastImpactPos):
    builder.PrependStructSlot(46, flatbuffers.number_types.UOffsetTFlags.py_type(lastImpactPos), 0)

def AddLastImpactPos(builder, lastImpactPos):
    TelemInfoAddLastImpactPos(builder, lastImpactPos)

def TelemInfoAddEngineTorque(builder, engineTorque):
    builder.PrependFloat64Slot(47, engineTorque, 0.0)

def AddEngineTorque(builder, engineTorque):
    TelemInfoAddEngineTorque(builder, engineTorque)

def TelemInfoAddCurrentSector(builder, currentSector):
    builder.PrependInt32Slot(48, currentSector, 0)

def AddCurrentSector(builder, currentSector):
    TelemInfoAddCurrentSector(builder, currentSector)

def TelemInfoAddSpeedLimiter(builder, speedLimiter):
    builder.PrependUint8Slot(49, speedLimiter, 0)

def AddSpeedLimiter(builder, speedLimiter):
    TelemInfoAddSpeedLimiter(builder, speedLimiter)

def TelemInfoAddMaxGears(builder, maxGears):
    builder.PrependUint8Slot(50, maxGears, 0)

def AddMaxGears(builder, maxGears):
    TelemInfoAddMaxGears(builder, maxGears)

def TelemInfoAddFrontTireCompoundIndex(builder, frontTireCompoundIndex):
    builder.PrependUint8Slot(51, frontTireCompoundIndex, 0)

def AddFrontTireCompoundIndex(builder, frontTireCompoundIndex):
    TelemInfoAddFrontTireCompoundIndex(builder, frontTireCompoundIndex)

def TelemInfoAddRearTireCompoundIndex(builder, rearTireCompoundIndex):
    builder.PrependUint8Slot(52, rearTireCompoundIndex, 0)

def AddRearTireCompoundIndex(builder, rearTireCompoundIndex):
    TelemInfoAddRearTireCompoundIndex(builder, rearTireCompoundIndex)

def TelemInfoAddFuelCapacity(builder, fuelCapacity):
    builder.PrependFloat64Slot(53, fuelCapacity, 0.0)

def AddFuelCapacity(builder, fuelCapacity):
    TelemInfoAddFuelCapacity(builder, fuelCapacity)

def TelemInfoAddFrontFlapActivated(builder, frontFlapActivated):
    builder.PrependUint8Slot(54, frontFlapActivated, 0)

def AddFrontFlapActivated(builder, frontFlapActivated):
    TelemInfoAddFrontFlapActivated(builder, frontFlapActivated)

def TelemInfoAddRearFlapActivated(builder, rearFlapActivated):
    builder.PrependUint8Slot(55, rearFlapActivated, 0)

def AddRearFlapActivated(builder, rearFlapActivated):
    TelemInfoAddRearFlapActivated(builder, rearFlapActivated)

def TelemInfoAddRearFlapLegalStatus(builder, rearFlapLegalStatus):
    builder.PrependUint8Slot(56, rearFlapLegalStatus, 0)

def AddRearFlapLegalStatus(builder, rearFlapLegalStatus):
    TelemInfoAddRearFlapLegalStatus(builder, rearFlapLegalStatus)

def TelemInfoAddIgnitionStarter(builder, ignitionStarter):
    builder.PrependUint8Slot(57, ignitionStarter, 0)

def AddIgnitionStarter(builder, ignitionStarter):
    TelemInfoAddIgnitionStarter(builder, ignitionStarter)

def TelemInfoAddFrontTireCompoundName(builder, frontTireCompoundName):
    builder.PrependUOffsetTRelativeSlot(58, flatbuffers.number_types.UOffsetTFlags.py_type(frontTireCompoundName), 0)

def AddFrontTireCompoundName(builder, frontTireCompoundName):
    TelemInfoAddFrontTireCompoundName(builder, frontTireCompoundName)

def TelemInfoAddRearTireCompoundName(builder, rearTireCompoundName):
    builder.PrependUOffsetTRelativeSlot(59, flatbuffers.number_types.UOffsetTFlags.py_type(rearTireCompoundName), 0)

def AddRearTireCompoundName(builder, rearTireCompoundName):
    TelemInfoAddRearTireCompoundName(builder, rearTireCompoundName)

def TelemInfoAddSpeedLimiterAvailable(builder, speedLimiterAvailable):
    builder.PrependUint8Slot(60, speedLimiterAvailable, 0)

def AddSpeedLimiterAvailable(builder, speedLimiterAvailable):
    TelemInfoAddSpeedLimiterAvailable(builder, speedLimiterAvailable)

def TelemInfoAddAntiStallActivated(builder, antiStallActivated):
    builder.PrependUint8Slot(61, antiStallActivated, 0)

def AddAntiStallActivated(builder, antiStallActivated):
    TelemInfoAddAntiStallActivated(builder, antiStallActivated)

def TelemInfoAddVisualSteeringWheelRange(builder, visualSteeringWheelRange):
    builder.PrependFloat32Slot(62, visualSteeringWheelRange, 0.0)

def AddVisualSteeringWheelRange(builder, visualSteeringWheelRange):
    TelemInfoAddVisualSteeringWheelRange(builder, visualSteeringWheelRange)

def TelemInfoAddRearBrakeBias(builder, rearBrakeBias):
    builder.PrependFloat64Slot(63, rearBrakeBias, 0.0)

def AddRearBrakeBias(builder, rearBrakeBias):
    TelemInfoAddRearBrakeBias(builder, rearBrakeBias)

def TelemInfoAddTurboBoostPressure(builder, turboBoostPressure):
    builder.PrependFloat64Slot(64, turboBoostPressure, 0.0)

def AddTurboBoostPressure(builder, turboBoostPressure):
    TelemInfoAddTurboBoostPressure(builder, turboBoostPressure)

def TelemInfoAddPhysicsToGraphicsOffset(builder, physicsToGraphicsOffset):
    builder.PrependUOffsetTRelativeSlot(65, flatbuffers.number_types.UOffsetTFlags.py_type(physicsToGraphicsOffset), 0)

def AddPhysicsToGraphicsOffset(builder, physicsToGraphicsOffset):
    TelemInfoAddPhysicsToGraphicsOffset(builder, physicsToGraphicsOffset)

def TelemInfoStartPhysicsToGraphicsOffsetVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartPhysicsToGraphicsOffsetVector(builder, numElems: int) -> int:
    return TelemInfoStartPhysicsToGraphicsOffsetVector(builder, numElems)

def TelemInfoAddPhysicalSteeringWheelRange(builder, physicalSteeringWheelRange):
    builder.PrependFloat32Slot(66, physicalSteeringWheelRange, 0.0)

def AddPhysicalSteeringWheelRange(builder, physicalSteeringWheelRange):
    TelemInfoAddPhysicalSteeringWheelRange(builder, physicalSteeringWheelRange)

def TelemInfoAddBatteryChargeFraction(builder, batteryChargeFraction):
    builder.PrependFloat64Slot(67, batteryChargeFraction, 0.0)

def AddBatteryChargeFraction(builder, batteryChargeFraction):
    TelemInfoAddBatteryChargeFraction(builder, batteryChargeFraction)

def TelemInfoAddElectricBoostMotorTorque(builder, electricBoostMotorTorque):
    builder.PrependFloat64Slot(68, electricBoostMotorTorque, 0.0)

def AddElectricBoostMotorTorque(builder, electricBoostMotorTorque):
    TelemInfoAddElectricBoostMotorTorque(builder, electricBoostMotorTorque)

def TelemInfoAddElectricBoostMotorRpm(builder, electricBoostMotorRpm):
    builder.PrependFloat64Slot(69, electricBoostMotorRpm, 0.0)

def AddElectricBoostMotorRpm(builder, electricBoostMotorRpm):
    TelemInfoAddElectricBoostMotorRpm(builder, electricBoostMotorRpm)

def TelemInfoAddElectricBoostMotorTemperature(builder, electricBoostMotorTemperature):
    builder.PrependFloat64Slot(70, electricBoostMotorTemperature, 0.0)

def AddElectricBoostMotorTemperature(builder, electricBoostMotorTemperature):
    TelemInfoAddElectricBoostMotorTemperature(builder, electricBoostMotorTemperature)

def TelemInfoAddElectricBoostWaterTemperature(builder, electricBoostWaterTemperature):
    builder.PrependFloat64Slot(71, electricBoostWaterTemperature, 0.0)

def AddElectricBoostWaterTemperature(builder, electricBoostWaterTemperature):
    TelemInfoAddElectricBoostWaterTemperature(builder, electricBoostWaterTemperature)

def TelemInfoAddElectricBoostMotorState(builder, electricBoostMotorState):
    builder.PrependUint8Slot(72, electricBoostMotorState, 0)

def AddElectricBoostMotorState(builder, electricBoostMotorState):
    TelemInfoAddElectricBoostMotorState(builder, electricBoostMotorState)

def TelemInfoAddLmu(builder, lmu):
    builder.PrependUOffsetTRelativeSlot(73, flatbuffers.number_types.UOffsetTFlags.py_type(lmu), 0)

def AddLmu(builder, lmu):
    TelemInfoAddLmu(builder, lmu)

def TelemInfoAddWheels(builder, wheels):
    builder.PrependUOffsetTRelativeSlot(74, flatbuffers.number_types.UOffsetTFlags.py_type(wheels), 0)

def AddWheels(builder, wheels):
    TelemInfoAddWheels(builder, wheels)

def TelemInfoStartWheelsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartWheelsVector(builder, numElems: int) -> int:
    return TelemInfoStartWheelsVector(builder, numElems)

def TelemInfoEnd(builder):
    return builder.EndObject()

def End(builder):
    return TelemInfoEnd(builder)
