# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TelemWheel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TelemWheel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTelemWheel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TelemWheel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TelemWheel
    def SuspensionDeflection(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemWheel
    def RideHeight(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemWheel
    def SuspForce(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemWheel
    def BrakeTemp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemWheel
    def BrakePressure(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemWheel
    def Rotation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemWheel
    def LateralPatchVel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemWheel
    def LongitudinalPatchVel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemWheel
    def LateralGroundVel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemWheel
    def LongitudinalGroundVel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemWheel
    def Camber(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemWheel
    def LateralForce(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemWheel
    def LongitudinalForce(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemWheel
    def TireLoad(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemWheel
    def GripFraction(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemWheel
    def Pressure(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemWheel
    def Temperature(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # TelemWheel
    def TemperatureAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float64Flags, o)
        return 0

    # TelemWheel
    def TemperatureLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TelemWheel
    def TemperatureIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        return o == 0

    # TelemWheel
    def Wear(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemWheel
    def TerrainName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # TelemWheel
    def SurfaceType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # TelemWheel
    def Flat(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # TelemWheel
    def Detached(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # TelemWheel
    def StaticUndeflectedRadius(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(48))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # TelemWheel
    def VerticalTireDeflection(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(50))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemWheel
    def WheelYLocation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemWheel
    def Toe(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(54))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemWheel
    def TireCarcassTemperature(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(56))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TelemWheel
    def TireInnerLayerTemperature(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(58))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # TelemWheel
    def TireInnerLayerTemperatureAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(58))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float64Flags, o)
        return 0

    # TelemWheel
    def TireInnerLayerTemperatureLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(58))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TelemWheel
    def TireInnerLayerTemperatureIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(58))
        return o == 0

    # TelemWheel
    def Lmu(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(60))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from isimotor_rawudp_types.fbs_generated.isimotor.fbs.LmuWheel import LmuWheel
            obj = LmuWheel()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def TelemWheelStart(builder):
    builder.StartObject(29)

def Start(builder):
    TelemWheelStart(builder)

def TelemWheelAddSuspensionDeflection(builder, suspensionDeflection):
    builder.PrependFloat64Slot(0, suspensionDeflection, 0.0)

def AddSuspensionDeflection(builder, suspensionDeflection):
    TelemWheelAddSuspensionDeflection(builder, suspensionDeflection)

def TelemWheelAddRideHeight(builder, rideHeight):
    builder.PrependFloat64Slot(1, rideHeight, 0.0)

def AddRideHeight(builder, rideHeight):
    TelemWheelAddRideHeight(builder, rideHeight)

def TelemWheelAddSuspForce(builder, suspForce):
    builder.PrependFloat64Slot(2, suspForce, 0.0)

def AddSuspForce(builder, suspForce):
    TelemWheelAddSuspForce(builder, suspForce)

def TelemWheelAddBrakeTemp(builder, brakeTemp):
    builder.PrependFloat64Slot(3, brakeTemp, 0.0)

def AddBrakeTemp(builder, brakeTemp):
    TelemWheelAddBrakeTemp(builder, brakeTemp)

def TelemWheelAddBrakePressure(builder, brakePressure):
    builder.PrependFloat64Slot(4, brakePressure, 0.0)

def AddBrakePressure(builder, brakePressure):
    TelemWheelAddBrakePressure(builder, brakePressure)

def TelemWheelAddRotation(builder, rotation):
    builder.PrependFloat64Slot(5, rotation, 0.0)

def AddRotation(builder, rotation):
    TelemWheelAddRotation(builder, rotation)

def TelemWheelAddLateralPatchVel(builder, lateralPatchVel):
    builder.PrependFloat64Slot(6, lateralPatchVel, 0.0)

def AddLateralPatchVel(builder, lateralPatchVel):
    TelemWheelAddLateralPatchVel(builder, lateralPatchVel)

def TelemWheelAddLongitudinalPatchVel(builder, longitudinalPatchVel):
    builder.PrependFloat64Slot(7, longitudinalPatchVel, 0.0)

def AddLongitudinalPatchVel(builder, longitudinalPatchVel):
    TelemWheelAddLongitudinalPatchVel(builder, longitudinalPatchVel)

def TelemWheelAddLateralGroundVel(builder, lateralGroundVel):
    builder.PrependFloat64Slot(8, lateralGroundVel, 0.0)

def AddLateralGroundVel(builder, lateralGroundVel):
    TelemWheelAddLateralGroundVel(builder, lateralGroundVel)

def TelemWheelAddLongitudinalGroundVel(builder, longitudinalGroundVel):
    builder.PrependFloat64Slot(9, longitudinalGroundVel, 0.0)

def AddLongitudinalGroundVel(builder, longitudinalGroundVel):
    TelemWheelAddLongitudinalGroundVel(builder, longitudinalGroundVel)

def TelemWheelAddCamber(builder, camber):
    builder.PrependFloat64Slot(10, camber, 0.0)

def AddCamber(builder, camber):
    TelemWheelAddCamber(builder, camber)

def TelemWheelAddLateralForce(builder, lateralForce):
    builder.PrependFloat64Slot(11, lateralForce, 0.0)

def AddLateralForce(builder, lateralForce):
    TelemWheelAddLateralForce(builder, lateralForce)

def TelemWheelAddLongitudinalForce(builder, longitudinalForce):
    builder.PrependFloat64Slot(12, longitudinalForce, 0.0)

def AddLongitudinalForce(builder, longitudinalForce):
    TelemWheelAddLongitudinalForce(builder, longitudinalForce)

def TelemWheelAddTireLoad(builder, tireLoad):
    builder.PrependFloat64Slot(13, tireLoad, 0.0)

def AddTireLoad(builder, tireLoad):
    TelemWheelAddTireLoad(builder, tireLoad)

def TelemWheelAddGripFraction(builder, gripFraction):
    builder.PrependFloat64Slot(14, gripFraction, 0.0)

def AddGripFraction(builder, gripFraction):
    TelemWheelAddGripFraction(builder, gripFraction)

def TelemWheelAddPressure(builder, pressure):
    builder.PrependFloat64Slot(15, pressure, 0.0)

def AddPressure(builder, pressure):
    TelemWheelAddPressure(builder, pressure)

def TelemWheelAddTemperature(builder, temperature):
    builder.PrependUOffsetTRelativeSlot(16, flatbuffers.number_types.UOffsetTFlags.py_type(temperature), 0)

def AddTemperature(builder, temperature):
    TelemWheelAddTemperature(builder, temperature)

def TelemWheelStartTemperatureVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def StartTemperatureVector(builder, numElems: int) -> int:
    return TelemWheelStartTemperatureVector(builder, numElems)

def TelemWheelAddWear(builder, wear):
    builder.PrependFloat64Slot(17, wear, 0.0)

def AddWear(builder, wear):
    TelemWheelAddWear(builder, wear)

def TelemWheelAddTerrainName(builder, terrainName):
    builder.PrependUOffsetTRelativeSlot(18, flatbuffers.number_types.UOffsetTFlags.py_type(terrainName), 0)

def AddTerrainName(builder, terrainName):
    TelemWheelAddTerrainName(builder, terrainName)

def TelemWheelAddSurfaceType(builder, surfaceType):
    builder.PrependUint8Slot(19, surfaceType, 0)

def AddSurfaceType(builder, surfaceType):
    TelemWheelAddSurfaceType(builder, surfaceType)

def TelemWheelAddFlat(builder, flat):
    builder.PrependBoolSlot(20, flat, 0)

def AddFlat(builder, flat):
    TelemWheelAddFlat(builder, flat)

def TelemWheelAddDetached(builder, detached):
    builder.PrependBoolSlot(21, detached, 0)

def AddDetached(builder, detached):
    TelemWheelAddDetached(builder, detached)

def TelemWheelAddStaticUndeflectedRadius(builder, staticUndeflectedRadius):
    builder.PrependUint8Slot(22, staticUndeflectedRadius, 0)

def AddStaticUndeflectedRadius(builder, staticUndeflectedRadius):
    TelemWheelAddStaticUndeflectedRadius(builder, staticUndeflectedRadius)

def TelemWheelAddVerticalTireDeflection(builder, verticalTireDeflection):
    builder.PrependFloat64Slot(23, verticalTireDeflection, 0.0)

def AddVerticalTireDeflection(builder, verticalTireDeflection):
    TelemWheelAddVerticalTireDeflection(builder, verticalTireDeflection)

def TelemWheelAddWheelYLocation(builder, wheelYLocation):
    builder.PrependFloat64Slot(24, wheelYLocation, 0.0)

def AddWheelYLocation(builder, wheelYLocation):
    TelemWheelAddWheelYLocation(builder, wheelYLocation)

def TelemWheelAddToe(builder, toe):
    builder.PrependFloat64Slot(25, toe, 0.0)

def AddToe(builder, toe):
    TelemWheelAddToe(builder, toe)

def TelemWheelAddTireCarcassTemperature(builder, tireCarcassTemperature):
    builder.PrependFloat64Slot(26, tireCarcassTemperature, 0.0)

def AddTireCarcassTemperature(builder, tireCarcassTemperature):
    TelemWheelAddTireCarcassTemperature(builder, tireCarcassTemperature)

def TelemWheelAddTireInnerLayerTemperature(builder, tireInnerLayerTemperature):
    builder.PrependUOffsetTRelativeSlot(27, flatbuffers.number_types.UOffsetTFlags.py_type(tireInnerLayerTemperature), 0)

def AddTireInnerLayerTemperature(builder, tireInnerLayerTemperature):
    TelemWheelAddTireInnerLayerTemperature(builder, tireInnerLayerTemperature)

def TelemWheelStartTireInnerLayerTemperatureVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def StartTireInnerLayerTemperatureVector(builder, numElems: int) -> int:
    return TelemWheelStartTireInnerLayerTemperatureVector(builder, numElems)

def TelemWheelAddLmu(builder, lmu):
    builder.PrependUOffsetTRelativeSlot(28, flatbuffers.number_types.UOffsetTFlags.py_type(lmu), 0)

def AddLmu(builder, lmu):
    TelemWheelAddLmu(builder, lmu)

def TelemWheelEnd(builder):
    return builder.EndObject()

def End(builder):
    return TelemWheelEnd(builder)
