# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WeatherControl(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WeatherControl()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWeatherControl(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WeatherControl
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WeatherControl
    def AmbientTemp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # WeatherControl
    def TrackTemp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # WeatherControl
    def DarkCloud(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # WeatherControl
    def Raining(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # WeatherControl
    def WindSpeed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # WeatherControl
    def WindDirection(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # WeatherControl
    def MinPathWetness(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # WeatherControl
    def MaxPathWetness(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def WeatherControlStart(builder):
    builder.StartObject(8)

def Start(builder):
    WeatherControlStart(builder)

def WeatherControlAddAmbientTemp(builder, ambientTemp):
    builder.PrependFloat64Slot(0, ambientTemp, 0.0)

def AddAmbientTemp(builder, ambientTemp):
    WeatherControlAddAmbientTemp(builder, ambientTemp)

def WeatherControlAddTrackTemp(builder, trackTemp):
    builder.PrependFloat64Slot(1, trackTemp, 0.0)

def AddTrackTemp(builder, trackTemp):
    WeatherControlAddTrackTemp(builder, trackTemp)

def WeatherControlAddDarkCloud(builder, darkCloud):
    builder.PrependFloat64Slot(2, darkCloud, 0.0)

def AddDarkCloud(builder, darkCloud):
    WeatherControlAddDarkCloud(builder, darkCloud)

def WeatherControlAddRaining(builder, raining):
    builder.PrependFloat64Slot(3, raining, 0.0)

def AddRaining(builder, raining):
    WeatherControlAddRaining(builder, raining)

def WeatherControlAddWindSpeed(builder, windSpeed):
    builder.PrependFloat64Slot(4, windSpeed, 0.0)

def AddWindSpeed(builder, windSpeed):
    WeatherControlAddWindSpeed(builder, windSpeed)

def WeatherControlAddWindDirection(builder, windDirection):
    builder.PrependFloat64Slot(5, windDirection, 0.0)

def AddWindDirection(builder, windDirection):
    WeatherControlAddWindDirection(builder, windDirection)

def WeatherControlAddMinPathWetness(builder, minPathWetness):
    builder.PrependFloat64Slot(6, minPathWetness, 0.0)

def AddMinPathWetness(builder, minPathWetness):
    WeatherControlAddMinPathWetness(builder, minPathWetness)

def WeatherControlAddMaxPathWetness(builder, maxPathWetness):
    builder.PrependFloat64Slot(7, maxPathWetness, 0.0)

def AddMaxPathWetness(builder, maxPathWetness):
    WeatherControlAddMaxPathWetness(builder, maxPathWetness)

def WeatherControlEnd(builder):
    return builder.EndObject()

def End(builder):
    return WeatherControlEnd(builder)
