"""
High-performance binary decoders and encoders for isiMotor / LMU / rFactor 2 raw UDP packets.
"""

from ..constants import (
    HEADER_SIZE,
    HEADER_STRUCT,
    SYSTEM_EVENT_SIZE,
    SYSTEM_EVENT_STRUCT,
    TELEMINFO_SIZE,
    COMPACT_SCORING_SIZE,
    FULL_SCORING_SESSION_SIZE,
    VEHICLE_SCORING_SIZE,
    TRACK_RULES_PARTICIPANT_SIZE,
    TRACK_RULES_PARTICIPANT_STRUCT,
    TRACK_RULES_SESSION_SIZE,
    TRACK_RULES_SESSION_STRUCT,
    PIT_MENU_SIZE,
    PIT_MENU_STRUCT,
    WEATHER_SIZE,
    WEATHER_STRUCT,
    EXTENDED_STATE_SIZE,
    EXTENDED_STATE_STRUCT,
    FORCE_FEEDBACK_SIZE,
    FORCE_FEEDBACK_STRUCT,
    GRAPHICS_SIZE,
    GRAPHICS_STRUCT,
    HW_CONTROL_COMMAND_SIZE,
    HW_CONTROL_COMMAND_STRUCT,
    WEATHER_CONTROL_COMMAND_SIZE,
    WEATHER_CONTROL_COMMAND_STRUCT,
    PKT_TYPE_TELEMETRY,
    PKT_TYPE_COMPACT_SCORING,
    PKT_TYPE_SYSTEM_EVENT,
    PKT_TYPE_FULL_SCORING,
    PKT_TYPE_TRACK_RULES,
    PKT_TYPE_PIT_MENU,
    PKT_TYPE_WEATHER,
    PKT_TYPE_EXTENDED_STATE,
    PKT_TYPE_FORCE_FEEDBACK,
    PKT_TYPE_GRAPHICS,
    PKT_TYPE_HW_CONTROL,
    PKT_TYPE_WEATHER_CONTROL,
)
from .base import _decode_string
from .header import decode_header, encode_header
from .telemetry import decode_wheel, decode_telemetry
from .scoring import (
    decode_compact_scoring,
    decode_vehicle_scoring,
    decode_full_scoring,
)
from .rules import (
    decode_track_rules_participant,
    decode_track_rules,
)
from .pit import decode_pit_menu
from .weather import decode_weather
from .physics import decode_extended_state
from .feedback import decode_force_feedback
from .graphics import decode_graphics
from .events import decode_system_event
from .commands import (
    decode_hw_control,
    encode_hw_control,
    decode_weather_control,
    encode_weather_control,
)
from .packet_decoder import (
    decode_packet,
    PacketDecoderRegistry,
    AnyPacket,
)

__all__ = [
    "HEADER_SIZE",
    "HEADER_STRUCT",
    "SYSTEM_EVENT_SIZE",
    "SYSTEM_EVENT_STRUCT",
    "TELEMINFO_SIZE",
    "COMPACT_SCORING_SIZE",
    "FULL_SCORING_SESSION_SIZE",
    "VEHICLE_SCORING_SIZE",
    "TRACK_RULES_PARTICIPANT_SIZE",
    "TRACK_RULES_PARTICIPANT_STRUCT",
    "TRACK_RULES_SESSION_SIZE",
    "TRACK_RULES_SESSION_STRUCT",
    "PIT_MENU_SIZE",
    "PIT_MENU_STRUCT",
    "WEATHER_SIZE",
    "WEATHER_STRUCT",
    "EXTENDED_STATE_SIZE",
    "EXTENDED_STATE_STRUCT",
    "FORCE_FEEDBACK_SIZE",
    "FORCE_FEEDBACK_STRUCT",
    "GRAPHICS_SIZE",
    "GRAPHICS_STRUCT",
    "HW_CONTROL_COMMAND_SIZE",
    "HW_CONTROL_COMMAND_STRUCT",
    "WEATHER_CONTROL_COMMAND_SIZE",
    "WEATHER_CONTROL_COMMAND_STRUCT",
    "PKT_TYPE_TELEMETRY",
    "PKT_TYPE_COMPACT_SCORING",
    "PKT_TYPE_SYSTEM_EVENT",
    "PKT_TYPE_FULL_SCORING",
    "PKT_TYPE_TRACK_RULES",
    "PKT_TYPE_PIT_MENU",
    "PKT_TYPE_WEATHER",
    "PKT_TYPE_EXTENDED_STATE",
    "PKT_TYPE_FORCE_FEEDBACK",
    "PKT_TYPE_GRAPHICS",
    "PKT_TYPE_HW_CONTROL",
    "PKT_TYPE_WEATHER_CONTROL",
    "_decode_string",
    "decode_header",
    "encode_header",
    "decode_wheel",
    "decode_telemetry",
    "decode_compact_scoring",
    "decode_vehicle_scoring",
    "decode_full_scoring",
    "decode_track_rules_participant",
    "decode_track_rules",
    "decode_pit_menu",
    "decode_weather",
    "decode_extended_state",
    "decode_force_feedback",
    "decode_graphics",
    "decode_system_event",
    "decode_hw_control",
    "encode_hw_control",
    "decode_weather_control",
    "encode_weather_control",
    "decode_packet",
    "PacketDecoderRegistry",
    "AnyPacket",
]
