// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_COMPACTSCORING_ISIMOTOR_FBS_H_
#define FLATBUFFERS_GENERATED_COMPACTSCORING_ISIMOTOR_FBS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

namespace isimotor {
namespace fbs {

struct CompactScoring;
struct CompactScoringBuilder;
struct CompactScoringT;

struct CompactScoringT : public ::flatbuffers::NativeTable {
  typedef CompactScoring TableType;
  std::string track_name{};
  int32_t session = 0;
  double current_et = 0.0;
  double total_lap_dist = 0.0;
  int32_t max_laps = 0;
  bool in_realtime = false;
  int16_t total_laps = 0;
  int8_t sector = 0;
  bool in_garage_stall = false;
  uint8_t count_lap_flag = 0;
  double cur_sector1 = 0.0;
  double cur_sector2 = 0.0;
  double last_sector1 = 0.0;
  double last_sector2 = 0.0;
  double last_lap_time = 0.0;
  double best_sector1 = 0.0;
  double best_sector2 = 0.0;
  double best_lap_time = 0.0;
};

struct CompactScoring FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CompactScoringT NativeTableType;
  typedef CompactScoringBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TRACK_NAME = 4,
    VT_SESSION = 6,
    VT_CURRENT_ET = 8,
    VT_TOTAL_LAP_DIST = 10,
    VT_MAX_LAPS = 12,
    VT_IN_REALTIME = 14,
    VT_TOTAL_LAPS = 16,
    VT_SECTOR = 18,
    VT_IN_GARAGE_STALL = 20,
    VT_COUNT_LAP_FLAG = 22,
    VT_CUR_SECTOR1 = 24,
    VT_CUR_SECTOR2 = 26,
    VT_LAST_SECTOR1 = 28,
    VT_LAST_SECTOR2 = 30,
    VT_LAST_LAP_TIME = 32,
    VT_BEST_SECTOR1 = 34,
    VT_BEST_SECTOR2 = 36,
    VT_BEST_LAP_TIME = 38
  };
  const ::flatbuffers::String *track_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TRACK_NAME);
  }
  int32_t session() const {
    return GetField<int32_t>(VT_SESSION, 0);
  }
  double current_et() const {
    return GetField<double>(VT_CURRENT_ET, 0.0);
  }
  double total_lap_dist() const {
    return GetField<double>(VT_TOTAL_LAP_DIST, 0.0);
  }
  int32_t max_laps() const {
    return GetField<int32_t>(VT_MAX_LAPS, 0);
  }
  bool in_realtime() const {
    return GetField<uint8_t>(VT_IN_REALTIME, 0) != 0;
  }
  int16_t total_laps() const {
    return GetField<int16_t>(VT_TOTAL_LAPS, 0);
  }
  int8_t sector() const {
    return GetField<int8_t>(VT_SECTOR, 0);
  }
  bool in_garage_stall() const {
    return GetField<uint8_t>(VT_IN_GARAGE_STALL, 0) != 0;
  }
  uint8_t count_lap_flag() const {
    return GetField<uint8_t>(VT_COUNT_LAP_FLAG, 0);
  }
  double cur_sector1() const {
    return GetField<double>(VT_CUR_SECTOR1, 0.0);
  }
  double cur_sector2() const {
    return GetField<double>(VT_CUR_SECTOR2, 0.0);
  }
  double last_sector1() const {
    return GetField<double>(VT_LAST_SECTOR1, 0.0);
  }
  double last_sector2() const {
    return GetField<double>(VT_LAST_SECTOR2, 0.0);
  }
  double last_lap_time() const {
    return GetField<double>(VT_LAST_LAP_TIME, 0.0);
  }
  double best_sector1() const {
    return GetField<double>(VT_BEST_SECTOR1, 0.0);
  }
  double best_sector2() const {
    return GetField<double>(VT_BEST_SECTOR2, 0.0);
  }
  double best_lap_time() const {
    return GetField<double>(VT_BEST_LAP_TIME, 0.0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_TRACK_NAME) &&
           verifier.VerifyString(track_name()) &&
           VerifyField<int32_t>(verifier, VT_SESSION, 4) &&
           VerifyField<double>(verifier, VT_CURRENT_ET, 8) &&
           VerifyField<double>(verifier, VT_TOTAL_LAP_DIST, 8) &&
           VerifyField<int32_t>(verifier, VT_MAX_LAPS, 4) &&
           VerifyField<uint8_t>(verifier, VT_IN_REALTIME, 1) &&
           VerifyField<int16_t>(verifier, VT_TOTAL_LAPS, 2) &&
           VerifyField<int8_t>(verifier, VT_SECTOR, 1) &&
           VerifyField<uint8_t>(verifier, VT_IN_GARAGE_STALL, 1) &&
           VerifyField<uint8_t>(verifier, VT_COUNT_LAP_FLAG, 1) &&
           VerifyField<double>(verifier, VT_CUR_SECTOR1, 8) &&
           VerifyField<double>(verifier, VT_CUR_SECTOR2, 8) &&
           VerifyField<double>(verifier, VT_LAST_SECTOR1, 8) &&
           VerifyField<double>(verifier, VT_LAST_SECTOR2, 8) &&
           VerifyField<double>(verifier, VT_LAST_LAP_TIME, 8) &&
           VerifyField<double>(verifier, VT_BEST_SECTOR1, 8) &&
           VerifyField<double>(verifier, VT_BEST_SECTOR2, 8) &&
           VerifyField<double>(verifier, VT_BEST_LAP_TIME, 8) &&
           verifier.EndTable();
  }
  CompactScoringT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CompactScoringT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<CompactScoring> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CompactScoringT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CompactScoringBuilder {
  typedef CompactScoring Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_track_name(::flatbuffers::Offset<::flatbuffers::String> track_name) {
    fbb_.AddOffset(CompactScoring::VT_TRACK_NAME, track_name);
  }
  void add_session(int32_t session) {
    fbb_.AddElement<int32_t>(CompactScoring::VT_SESSION, session, 0);
  }
  void add_current_et(double current_et) {
    fbb_.AddElement<double>(CompactScoring::VT_CURRENT_ET, current_et, 0.0);
  }
  void add_total_lap_dist(double total_lap_dist) {
    fbb_.AddElement<double>(CompactScoring::VT_TOTAL_LAP_DIST, total_lap_dist, 0.0);
  }
  void add_max_laps(int32_t max_laps) {
    fbb_.AddElement<int32_t>(CompactScoring::VT_MAX_LAPS, max_laps, 0);
  }
  void add_in_realtime(bool in_realtime) {
    fbb_.AddElement<uint8_t>(CompactScoring::VT_IN_REALTIME, static_cast<uint8_t>(in_realtime), 0);
  }
  void add_total_laps(int16_t total_laps) {
    fbb_.AddElement<int16_t>(CompactScoring::VT_TOTAL_LAPS, total_laps, 0);
  }
  void add_sector(int8_t sector) {
    fbb_.AddElement<int8_t>(CompactScoring::VT_SECTOR, sector, 0);
  }
  void add_in_garage_stall(bool in_garage_stall) {
    fbb_.AddElement<uint8_t>(CompactScoring::VT_IN_GARAGE_STALL, static_cast<uint8_t>(in_garage_stall), 0);
  }
  void add_count_lap_flag(uint8_t count_lap_flag) {
    fbb_.AddElement<uint8_t>(CompactScoring::VT_COUNT_LAP_FLAG, count_lap_flag, 0);
  }
  void add_cur_sector1(double cur_sector1) {
    fbb_.AddElement<double>(CompactScoring::VT_CUR_SECTOR1, cur_sector1, 0.0);
  }
  void add_cur_sector2(double cur_sector2) {
    fbb_.AddElement<double>(CompactScoring::VT_CUR_SECTOR2, cur_sector2, 0.0);
  }
  void add_last_sector1(double last_sector1) {
    fbb_.AddElement<double>(CompactScoring::VT_LAST_SECTOR1, last_sector1, 0.0);
  }
  void add_last_sector2(double last_sector2) {
    fbb_.AddElement<double>(CompactScoring::VT_LAST_SECTOR2, last_sector2, 0.0);
  }
  void add_last_lap_time(double last_lap_time) {
    fbb_.AddElement<double>(CompactScoring::VT_LAST_LAP_TIME, last_lap_time, 0.0);
  }
  void add_best_sector1(double best_sector1) {
    fbb_.AddElement<double>(CompactScoring::VT_BEST_SECTOR1, best_sector1, 0.0);
  }
  void add_best_sector2(double best_sector2) {
    fbb_.AddElement<double>(CompactScoring::VT_BEST_SECTOR2, best_sector2, 0.0);
  }
  void add_best_lap_time(double best_lap_time) {
    fbb_.AddElement<double>(CompactScoring::VT_BEST_LAP_TIME, best_lap_time, 0.0);
  }
  explicit CompactScoringBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CompactScoring> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CompactScoring>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CompactScoring> CreateCompactScoring(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> track_name = 0,
    int32_t session = 0,
    double current_et = 0.0,
    double total_lap_dist = 0.0,
    int32_t max_laps = 0,
    bool in_realtime = false,
    int16_t total_laps = 0,
    int8_t sector = 0,
    bool in_garage_stall = false,
    uint8_t count_lap_flag = 0,
    double cur_sector1 = 0.0,
    double cur_sector2 = 0.0,
    double last_sector1 = 0.0,
    double last_sector2 = 0.0,
    double last_lap_time = 0.0,
    double best_sector1 = 0.0,
    double best_sector2 = 0.0,
    double best_lap_time = 0.0) {
  CompactScoringBuilder builder_(_fbb);
  builder_.add_best_lap_time(best_lap_time);
  builder_.add_best_sector2(best_sector2);
  builder_.add_best_sector1(best_sector1);
  builder_.add_last_lap_time(last_lap_time);
  builder_.add_last_sector2(last_sector2);
  builder_.add_last_sector1(last_sector1);
  builder_.add_cur_sector2(cur_sector2);
  builder_.add_cur_sector1(cur_sector1);
  builder_.add_total_lap_dist(total_lap_dist);
  builder_.add_current_et(current_et);
  builder_.add_max_laps(max_laps);
  builder_.add_session(session);
  builder_.add_track_name(track_name);
  builder_.add_total_laps(total_laps);
  builder_.add_count_lap_flag(count_lap_flag);
  builder_.add_in_garage_stall(in_garage_stall);
  builder_.add_sector(sector);
  builder_.add_in_realtime(in_realtime);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CompactScoring> CreateCompactScoringDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *track_name = nullptr,
    int32_t session = 0,
    double current_et = 0.0,
    double total_lap_dist = 0.0,
    int32_t max_laps = 0,
    bool in_realtime = false,
    int16_t total_laps = 0,
    int8_t sector = 0,
    bool in_garage_stall = false,
    uint8_t count_lap_flag = 0,
    double cur_sector1 = 0.0,
    double cur_sector2 = 0.0,
    double last_sector1 = 0.0,
    double last_sector2 = 0.0,
    double last_lap_time = 0.0,
    double best_sector1 = 0.0,
    double best_sector2 = 0.0,
    double best_lap_time = 0.0) {
  auto track_name__ = track_name ? _fbb.CreateString(track_name) : 0;
  return isimotor::fbs::CreateCompactScoring(
      _fbb,
      track_name__,
      session,
      current_et,
      total_lap_dist,
      max_laps,
      in_realtime,
      total_laps,
      sector,
      in_garage_stall,
      count_lap_flag,
      cur_sector1,
      cur_sector2,
      last_sector1,
      last_sector2,
      last_lap_time,
      best_sector1,
      best_sector2,
      best_lap_time);
}

::flatbuffers::Offset<CompactScoring> CreateCompactScoring(::flatbuffers::FlatBufferBuilder &_fbb, const CompactScoringT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline CompactScoringT *CompactScoring::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CompactScoringT>(new CompactScoringT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CompactScoring::UnPackTo(CompactScoringT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = track_name(); if (_e) _o->track_name = _e->str(); }
  { auto _e = session(); _o->session = _e; }
  { auto _e = current_et(); _o->current_et = _e; }
  { auto _e = total_lap_dist(); _o->total_lap_dist = _e; }
  { auto _e = max_laps(); _o->max_laps = _e; }
  { auto _e = in_realtime(); _o->in_realtime = _e; }
  { auto _e = total_laps(); _o->total_laps = _e; }
  { auto _e = sector(); _o->sector = _e; }
  { auto _e = in_garage_stall(); _o->in_garage_stall = _e; }
  { auto _e = count_lap_flag(); _o->count_lap_flag = _e; }
  { auto _e = cur_sector1(); _o->cur_sector1 = _e; }
  { auto _e = cur_sector2(); _o->cur_sector2 = _e; }
  { auto _e = last_sector1(); _o->last_sector1 = _e; }
  { auto _e = last_sector2(); _o->last_sector2 = _e; }
  { auto _e = last_lap_time(); _o->last_lap_time = _e; }
  { auto _e = best_sector1(); _o->best_sector1 = _e; }
  { auto _e = best_sector2(); _o->best_sector2 = _e; }
  { auto _e = best_lap_time(); _o->best_lap_time = _e; }
}

inline ::flatbuffers::Offset<CompactScoring> CompactScoring::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CompactScoringT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateCompactScoring(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<CompactScoring> CreateCompactScoring(::flatbuffers::FlatBufferBuilder &_fbb, const CompactScoringT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CompactScoringT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _track_name = _o->track_name.empty() ? 0 : _fbb.CreateString(_o->track_name);
  auto _session = _o->session;
  auto _current_et = _o->current_et;
  auto _total_lap_dist = _o->total_lap_dist;
  auto _max_laps = _o->max_laps;
  auto _in_realtime = _o->in_realtime;
  auto _total_laps = _o->total_laps;
  auto _sector = _o->sector;
  auto _in_garage_stall = _o->in_garage_stall;
  auto _count_lap_flag = _o->count_lap_flag;
  auto _cur_sector1 = _o->cur_sector1;
  auto _cur_sector2 = _o->cur_sector2;
  auto _last_sector1 = _o->last_sector1;
  auto _last_sector2 = _o->last_sector2;
  auto _last_lap_time = _o->last_lap_time;
  auto _best_sector1 = _o->best_sector1;
  auto _best_sector2 = _o->best_sector2;
  auto _best_lap_time = _o->best_lap_time;
  return isimotor::fbs::CreateCompactScoring(
      _fbb,
      _track_name,
      _session,
      _current_et,
      _total_lap_dist,
      _max_laps,
      _in_realtime,
      _total_laps,
      _sector,
      _in_garage_stall,
      _count_lap_flag,
      _cur_sector1,
      _cur_sector2,
      _last_sector1,
      _last_sector2,
      _last_lap_time,
      _best_sector1,
      _best_sector2,
      _best_lap_time);
}

inline const isimotor::fbs::CompactScoring *GetCompactScoring(const void *buf) {
  return ::flatbuffers::GetRoot<isimotor::fbs::CompactScoring>(buf);
}

inline const isimotor::fbs::CompactScoring *GetSizePrefixedCompactScoring(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<isimotor::fbs::CompactScoring>(buf);
}

inline bool VerifyCompactScoringBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<isimotor::fbs::CompactScoring>(nullptr);
}

inline bool VerifySizePrefixedCompactScoringBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<isimotor::fbs::CompactScoring>(nullptr);
}

inline void FinishCompactScoringBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<isimotor::fbs::CompactScoring> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedCompactScoringBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<isimotor::fbs::CompactScoring> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<isimotor::fbs::CompactScoringT> UnPackCompactScoring(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<isimotor::fbs::CompactScoringT>(GetCompactScoring(buf)->UnPack(res));
}

inline std::unique_ptr<isimotor::fbs::CompactScoringT> UnPackSizePrefixedCompactScoring(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<isimotor::fbs::CompactScoringT>(GetSizePrefixedCompactScoring(buf)->UnPack(res));
}

}  // namespace fbs
}  // namespace isimotor

#endif  // FLATBUFFERS_GENERATED_COMPACTSCORING_ISIMOTOR_FBS_H_
