// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_EXTENDEDSTATE_ISIMOTOR_FBS_H_
#define FLATBUFFERS_GENERATED_EXTENDEDSTATE_ISIMOTOR_FBS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

namespace isimotor {
namespace fbs {

struct PhysicsOptions;
struct PhysicsOptionsBuilder;
struct PhysicsOptionsT;

struct ExtendedState;
struct ExtendedStateBuilder;
struct ExtendedStateT;

struct PhysicsOptionsT : public ::flatbuffers::NativeTable {
  typedef PhysicsOptions TableType;
  uint8_t traction_control = 0;
  uint8_t anti_lock_brakes = 0;
  uint8_t stability_control = 0;
  uint8_t auto_shift = 0;
  uint8_t auto_clutch = 0;
  uint8_t invulnerable = 0;
  uint8_t opposite_lock = 0;
  uint8_t steering_help = 0;
  uint8_t braking_help = 0;
  uint8_t spin_recovery = 0;
  uint8_t auto_pit = 0;
  uint8_t auto_lift = 0;
  uint8_t auto_blip = 0;
  uint8_t fuel_mult = 0;
  uint8_t tire_mult = 0;
  uint8_t mech_fail = 0;
  uint8_t allow_pitcrew_push = 0;
  uint8_t repeat_shifts = 0;
  uint8_t hold_clutch = 0;
  uint8_t auto_reverse = 0;
  uint8_t alternate_neutral = 0;
  uint8_t ai_control = 0;
  float manual_shift_override_time = 0.0f;
  float auto_shift_override_time = 0.0f;
  float speed_sensitive_steering = 0.0f;
  float steer_ratio_speed = 0.0f;
};

struct PhysicsOptions FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PhysicsOptionsT NativeTableType;
  typedef PhysicsOptionsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TRACTION_CONTROL = 4,
    VT_ANTI_LOCK_BRAKES = 6,
    VT_STABILITY_CONTROL = 8,
    VT_AUTO_SHIFT = 10,
    VT_AUTO_CLUTCH = 12,
    VT_INVULNERABLE = 14,
    VT_OPPOSITE_LOCK = 16,
    VT_STEERING_HELP = 18,
    VT_BRAKING_HELP = 20,
    VT_SPIN_RECOVERY = 22,
    VT_AUTO_PIT = 24,
    VT_AUTO_LIFT = 26,
    VT_AUTO_BLIP = 28,
    VT_FUEL_MULT = 30,
    VT_TIRE_MULT = 32,
    VT_MECH_FAIL = 34,
    VT_ALLOW_PITCREW_PUSH = 36,
    VT_REPEAT_SHIFTS = 38,
    VT_HOLD_CLUTCH = 40,
    VT_AUTO_REVERSE = 42,
    VT_ALTERNATE_NEUTRAL = 44,
    VT_AI_CONTROL = 46,
    VT_MANUAL_SHIFT_OVERRIDE_TIME = 48,
    VT_AUTO_SHIFT_OVERRIDE_TIME = 50,
    VT_SPEED_SENSITIVE_STEERING = 52,
    VT_STEER_RATIO_SPEED = 54
  };
  uint8_t traction_control() const {
    return GetField<uint8_t>(VT_TRACTION_CONTROL, 0);
  }
  uint8_t anti_lock_brakes() const {
    return GetField<uint8_t>(VT_ANTI_LOCK_BRAKES, 0);
  }
  uint8_t stability_control() const {
    return GetField<uint8_t>(VT_STABILITY_CONTROL, 0);
  }
  uint8_t auto_shift() const {
    return GetField<uint8_t>(VT_AUTO_SHIFT, 0);
  }
  uint8_t auto_clutch() const {
    return GetField<uint8_t>(VT_AUTO_CLUTCH, 0);
  }
  uint8_t invulnerable() const {
    return GetField<uint8_t>(VT_INVULNERABLE, 0);
  }
  uint8_t opposite_lock() const {
    return GetField<uint8_t>(VT_OPPOSITE_LOCK, 0);
  }
  uint8_t steering_help() const {
    return GetField<uint8_t>(VT_STEERING_HELP, 0);
  }
  uint8_t braking_help() const {
    return GetField<uint8_t>(VT_BRAKING_HELP, 0);
  }
  uint8_t spin_recovery() const {
    return GetField<uint8_t>(VT_SPIN_RECOVERY, 0);
  }
  uint8_t auto_pit() const {
    return GetField<uint8_t>(VT_AUTO_PIT, 0);
  }
  uint8_t auto_lift() const {
    return GetField<uint8_t>(VT_AUTO_LIFT, 0);
  }
  uint8_t auto_blip() const {
    return GetField<uint8_t>(VT_AUTO_BLIP, 0);
  }
  uint8_t fuel_mult() const {
    return GetField<uint8_t>(VT_FUEL_MULT, 0);
  }
  uint8_t tire_mult() const {
    return GetField<uint8_t>(VT_TIRE_MULT, 0);
  }
  uint8_t mech_fail() const {
    return GetField<uint8_t>(VT_MECH_FAIL, 0);
  }
  uint8_t allow_pitcrew_push() const {
    return GetField<uint8_t>(VT_ALLOW_PITCREW_PUSH, 0);
  }
  uint8_t repeat_shifts() const {
    return GetField<uint8_t>(VT_REPEAT_SHIFTS, 0);
  }
  uint8_t hold_clutch() const {
    return GetField<uint8_t>(VT_HOLD_CLUTCH, 0);
  }
  uint8_t auto_reverse() const {
    return GetField<uint8_t>(VT_AUTO_REVERSE, 0);
  }
  uint8_t alternate_neutral() const {
    return GetField<uint8_t>(VT_ALTERNATE_NEUTRAL, 0);
  }
  uint8_t ai_control() const {
    return GetField<uint8_t>(VT_AI_CONTROL, 0);
  }
  float manual_shift_override_time() const {
    return GetField<float>(VT_MANUAL_SHIFT_OVERRIDE_TIME, 0.0f);
  }
  float auto_shift_override_time() const {
    return GetField<float>(VT_AUTO_SHIFT_OVERRIDE_TIME, 0.0f);
  }
  float speed_sensitive_steering() const {
    return GetField<float>(VT_SPEED_SENSITIVE_STEERING, 0.0f);
  }
  float steer_ratio_speed() const {
    return GetField<float>(VT_STEER_RATIO_SPEED, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_TRACTION_CONTROL, 1) &&
           VerifyField<uint8_t>(verifier, VT_ANTI_LOCK_BRAKES, 1) &&
           VerifyField<uint8_t>(verifier, VT_STABILITY_CONTROL, 1) &&
           VerifyField<uint8_t>(verifier, VT_AUTO_SHIFT, 1) &&
           VerifyField<uint8_t>(verifier, VT_AUTO_CLUTCH, 1) &&
           VerifyField<uint8_t>(verifier, VT_INVULNERABLE, 1) &&
           VerifyField<uint8_t>(verifier, VT_OPPOSITE_LOCK, 1) &&
           VerifyField<uint8_t>(verifier, VT_STEERING_HELP, 1) &&
           VerifyField<uint8_t>(verifier, VT_BRAKING_HELP, 1) &&
           VerifyField<uint8_t>(verifier, VT_SPIN_RECOVERY, 1) &&
           VerifyField<uint8_t>(verifier, VT_AUTO_PIT, 1) &&
           VerifyField<uint8_t>(verifier, VT_AUTO_LIFT, 1) &&
           VerifyField<uint8_t>(verifier, VT_AUTO_BLIP, 1) &&
           VerifyField<uint8_t>(verifier, VT_FUEL_MULT, 1) &&
           VerifyField<uint8_t>(verifier, VT_TIRE_MULT, 1) &&
           VerifyField<uint8_t>(verifier, VT_MECH_FAIL, 1) &&
           VerifyField<uint8_t>(verifier, VT_ALLOW_PITCREW_PUSH, 1) &&
           VerifyField<uint8_t>(verifier, VT_REPEAT_SHIFTS, 1) &&
           VerifyField<uint8_t>(verifier, VT_HOLD_CLUTCH, 1) &&
           VerifyField<uint8_t>(verifier, VT_AUTO_REVERSE, 1) &&
           VerifyField<uint8_t>(verifier, VT_ALTERNATE_NEUTRAL, 1) &&
           VerifyField<uint8_t>(verifier, VT_AI_CONTROL, 1) &&
           VerifyField<float>(verifier, VT_MANUAL_SHIFT_OVERRIDE_TIME, 4) &&
           VerifyField<float>(verifier, VT_AUTO_SHIFT_OVERRIDE_TIME, 4) &&
           VerifyField<float>(verifier, VT_SPEED_SENSITIVE_STEERING, 4) &&
           VerifyField<float>(verifier, VT_STEER_RATIO_SPEED, 4) &&
           verifier.EndTable();
  }
  PhysicsOptionsT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(PhysicsOptionsT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<PhysicsOptions> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const PhysicsOptionsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct PhysicsOptionsBuilder {
  typedef PhysicsOptions Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_traction_control(uint8_t traction_control) {
    fbb_.AddElement<uint8_t>(PhysicsOptions::VT_TRACTION_CONTROL, traction_control, 0);
  }
  void add_anti_lock_brakes(uint8_t anti_lock_brakes) {
    fbb_.AddElement<uint8_t>(PhysicsOptions::VT_ANTI_LOCK_BRAKES, anti_lock_brakes, 0);
  }
  void add_stability_control(uint8_t stability_control) {
    fbb_.AddElement<uint8_t>(PhysicsOptions::VT_STABILITY_CONTROL, stability_control, 0);
  }
  void add_auto_shift(uint8_t auto_shift) {
    fbb_.AddElement<uint8_t>(PhysicsOptions::VT_AUTO_SHIFT, auto_shift, 0);
  }
  void add_auto_clutch(uint8_t auto_clutch) {
    fbb_.AddElement<uint8_t>(PhysicsOptions::VT_AUTO_CLUTCH, auto_clutch, 0);
  }
  void add_invulnerable(uint8_t invulnerable) {
    fbb_.AddElement<uint8_t>(PhysicsOptions::VT_INVULNERABLE, invulnerable, 0);
  }
  void add_opposite_lock(uint8_t opposite_lock) {
    fbb_.AddElement<uint8_t>(PhysicsOptions::VT_OPPOSITE_LOCK, opposite_lock, 0);
  }
  void add_steering_help(uint8_t steering_help) {
    fbb_.AddElement<uint8_t>(PhysicsOptions::VT_STEERING_HELP, steering_help, 0);
  }
  void add_braking_help(uint8_t braking_help) {
    fbb_.AddElement<uint8_t>(PhysicsOptions::VT_BRAKING_HELP, braking_help, 0);
  }
  void add_spin_recovery(uint8_t spin_recovery) {
    fbb_.AddElement<uint8_t>(PhysicsOptions::VT_SPIN_RECOVERY, spin_recovery, 0);
  }
  void add_auto_pit(uint8_t auto_pit) {
    fbb_.AddElement<uint8_t>(PhysicsOptions::VT_AUTO_PIT, auto_pit, 0);
  }
  void add_auto_lift(uint8_t auto_lift) {
    fbb_.AddElement<uint8_t>(PhysicsOptions::VT_AUTO_LIFT, auto_lift, 0);
  }
  void add_auto_blip(uint8_t auto_blip) {
    fbb_.AddElement<uint8_t>(PhysicsOptions::VT_AUTO_BLIP, auto_blip, 0);
  }
  void add_fuel_mult(uint8_t fuel_mult) {
    fbb_.AddElement<uint8_t>(PhysicsOptions::VT_FUEL_MULT, fuel_mult, 0);
  }
  void add_tire_mult(uint8_t tire_mult) {
    fbb_.AddElement<uint8_t>(PhysicsOptions::VT_TIRE_MULT, tire_mult, 0);
  }
  void add_mech_fail(uint8_t mech_fail) {
    fbb_.AddElement<uint8_t>(PhysicsOptions::VT_MECH_FAIL, mech_fail, 0);
  }
  void add_allow_pitcrew_push(uint8_t allow_pitcrew_push) {
    fbb_.AddElement<uint8_t>(PhysicsOptions::VT_ALLOW_PITCREW_PUSH, allow_pitcrew_push, 0);
  }
  void add_repeat_shifts(uint8_t repeat_shifts) {
    fbb_.AddElement<uint8_t>(PhysicsOptions::VT_REPEAT_SHIFTS, repeat_shifts, 0);
  }
  void add_hold_clutch(uint8_t hold_clutch) {
    fbb_.AddElement<uint8_t>(PhysicsOptions::VT_HOLD_CLUTCH, hold_clutch, 0);
  }
  void add_auto_reverse(uint8_t auto_reverse) {
    fbb_.AddElement<uint8_t>(PhysicsOptions::VT_AUTO_REVERSE, auto_reverse, 0);
  }
  void add_alternate_neutral(uint8_t alternate_neutral) {
    fbb_.AddElement<uint8_t>(PhysicsOptions::VT_ALTERNATE_NEUTRAL, alternate_neutral, 0);
  }
  void add_ai_control(uint8_t ai_control) {
    fbb_.AddElement<uint8_t>(PhysicsOptions::VT_AI_CONTROL, ai_control, 0);
  }
  void add_manual_shift_override_time(float manual_shift_override_time) {
    fbb_.AddElement<float>(PhysicsOptions::VT_MANUAL_SHIFT_OVERRIDE_TIME, manual_shift_override_time, 0.0f);
  }
  void add_auto_shift_override_time(float auto_shift_override_time) {
    fbb_.AddElement<float>(PhysicsOptions::VT_AUTO_SHIFT_OVERRIDE_TIME, auto_shift_override_time, 0.0f);
  }
  void add_speed_sensitive_steering(float speed_sensitive_steering) {
    fbb_.AddElement<float>(PhysicsOptions::VT_SPEED_SENSITIVE_STEERING, speed_sensitive_steering, 0.0f);
  }
  void add_steer_ratio_speed(float steer_ratio_speed) {
    fbb_.AddElement<float>(PhysicsOptions::VT_STEER_RATIO_SPEED, steer_ratio_speed, 0.0f);
  }
  explicit PhysicsOptionsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PhysicsOptions> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PhysicsOptions>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PhysicsOptions> CreatePhysicsOptions(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t traction_control = 0,
    uint8_t anti_lock_brakes = 0,
    uint8_t stability_control = 0,
    uint8_t auto_shift = 0,
    uint8_t auto_clutch = 0,
    uint8_t invulnerable = 0,
    uint8_t opposite_lock = 0,
    uint8_t steering_help = 0,
    uint8_t braking_help = 0,
    uint8_t spin_recovery = 0,
    uint8_t auto_pit = 0,
    uint8_t auto_lift = 0,
    uint8_t auto_blip = 0,
    uint8_t fuel_mult = 0,
    uint8_t tire_mult = 0,
    uint8_t mech_fail = 0,
    uint8_t allow_pitcrew_push = 0,
    uint8_t repeat_shifts = 0,
    uint8_t hold_clutch = 0,
    uint8_t auto_reverse = 0,
    uint8_t alternate_neutral = 0,
    uint8_t ai_control = 0,
    float manual_shift_override_time = 0.0f,
    float auto_shift_override_time = 0.0f,
    float speed_sensitive_steering = 0.0f,
    float steer_ratio_speed = 0.0f) {
  PhysicsOptionsBuilder builder_(_fbb);
  builder_.add_steer_ratio_speed(steer_ratio_speed);
  builder_.add_speed_sensitive_steering(speed_sensitive_steering);
  builder_.add_auto_shift_override_time(auto_shift_override_time);
  builder_.add_manual_shift_override_time(manual_shift_override_time);
  builder_.add_ai_control(ai_control);
  builder_.add_alternate_neutral(alternate_neutral);
  builder_.add_auto_reverse(auto_reverse);
  builder_.add_hold_clutch(hold_clutch);
  builder_.add_repeat_shifts(repeat_shifts);
  builder_.add_allow_pitcrew_push(allow_pitcrew_push);
  builder_.add_mech_fail(mech_fail);
  builder_.add_tire_mult(tire_mult);
  builder_.add_fuel_mult(fuel_mult);
  builder_.add_auto_blip(auto_blip);
  builder_.add_auto_lift(auto_lift);
  builder_.add_auto_pit(auto_pit);
  builder_.add_spin_recovery(spin_recovery);
  builder_.add_braking_help(braking_help);
  builder_.add_steering_help(steering_help);
  builder_.add_opposite_lock(opposite_lock);
  builder_.add_invulnerable(invulnerable);
  builder_.add_auto_clutch(auto_clutch);
  builder_.add_auto_shift(auto_shift);
  builder_.add_stability_control(stability_control);
  builder_.add_anti_lock_brakes(anti_lock_brakes);
  builder_.add_traction_control(traction_control);
  return builder_.Finish();
}

::flatbuffers::Offset<PhysicsOptions> CreatePhysicsOptions(::flatbuffers::FlatBufferBuilder &_fbb, const PhysicsOptionsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ExtendedStateT : public ::flatbuffers::NativeTable {
  typedef ExtendedState TableType;
  std::unique_ptr<isimotor::fbs::PhysicsOptionsT> physics{};
  double max_impact_magnitude = 0.0;
  double accumulated_impact_magnitude = 0.0;
  bool in_realtime_fc = false;
  bool session_started = false;
  int32_t session = 0;
  float current_pit_speed_limit = 0.0f;
  ExtendedStateT() = default;
  ExtendedStateT(const ExtendedStateT &o);
  ExtendedStateT(ExtendedStateT&&) FLATBUFFERS_NOEXCEPT = default;
  ExtendedStateT &operator=(ExtendedStateT o) FLATBUFFERS_NOEXCEPT;
};

struct ExtendedState FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ExtendedStateT NativeTableType;
  typedef ExtendedStateBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PHYSICS = 4,
    VT_MAX_IMPACT_MAGNITUDE = 6,
    VT_ACCUMULATED_IMPACT_MAGNITUDE = 8,
    VT_IN_REALTIME_FC = 10,
    VT_SESSION_STARTED = 12,
    VT_SESSION = 14,
    VT_CURRENT_PIT_SPEED_LIMIT = 16
  };
  const isimotor::fbs::PhysicsOptions *physics() const {
    return GetPointer<const isimotor::fbs::PhysicsOptions *>(VT_PHYSICS);
  }
  double max_impact_magnitude() const {
    return GetField<double>(VT_MAX_IMPACT_MAGNITUDE, 0.0);
  }
  double accumulated_impact_magnitude() const {
    return GetField<double>(VT_ACCUMULATED_IMPACT_MAGNITUDE, 0.0);
  }
  bool in_realtime_fc() const {
    return GetField<uint8_t>(VT_IN_REALTIME_FC, 0) != 0;
  }
  bool session_started() const {
    return GetField<uint8_t>(VT_SESSION_STARTED, 0) != 0;
  }
  int32_t session() const {
    return GetField<int32_t>(VT_SESSION, 0);
  }
  float current_pit_speed_limit() const {
    return GetField<float>(VT_CURRENT_PIT_SPEED_LIMIT, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PHYSICS) &&
           verifier.VerifyTable(physics()) &&
           VerifyField<double>(verifier, VT_MAX_IMPACT_MAGNITUDE, 8) &&
           VerifyField<double>(verifier, VT_ACCUMULATED_IMPACT_MAGNITUDE, 8) &&
           VerifyField<uint8_t>(verifier, VT_IN_REALTIME_FC, 1) &&
           VerifyField<uint8_t>(verifier, VT_SESSION_STARTED, 1) &&
           VerifyField<int32_t>(verifier, VT_SESSION, 4) &&
           VerifyField<float>(verifier, VT_CURRENT_PIT_SPEED_LIMIT, 4) &&
           verifier.EndTable();
  }
  ExtendedStateT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ExtendedStateT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ExtendedState> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ExtendedStateT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ExtendedStateBuilder {
  typedef ExtendedState Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_physics(::flatbuffers::Offset<isimotor::fbs::PhysicsOptions> physics) {
    fbb_.AddOffset(ExtendedState::VT_PHYSICS, physics);
  }
  void add_max_impact_magnitude(double max_impact_magnitude) {
    fbb_.AddElement<double>(ExtendedState::VT_MAX_IMPACT_MAGNITUDE, max_impact_magnitude, 0.0);
  }
  void add_accumulated_impact_magnitude(double accumulated_impact_magnitude) {
    fbb_.AddElement<double>(ExtendedState::VT_ACCUMULATED_IMPACT_MAGNITUDE, accumulated_impact_magnitude, 0.0);
  }
  void add_in_realtime_fc(bool in_realtime_fc) {
    fbb_.AddElement<uint8_t>(ExtendedState::VT_IN_REALTIME_FC, static_cast<uint8_t>(in_realtime_fc), 0);
  }
  void add_session_started(bool session_started) {
    fbb_.AddElement<uint8_t>(ExtendedState::VT_SESSION_STARTED, static_cast<uint8_t>(session_started), 0);
  }
  void add_session(int32_t session) {
    fbb_.AddElement<int32_t>(ExtendedState::VT_SESSION, session, 0);
  }
  void add_current_pit_speed_limit(float current_pit_speed_limit) {
    fbb_.AddElement<float>(ExtendedState::VT_CURRENT_PIT_SPEED_LIMIT, current_pit_speed_limit, 0.0f);
  }
  explicit ExtendedStateBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ExtendedState> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ExtendedState>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ExtendedState> CreateExtendedState(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<isimotor::fbs::PhysicsOptions> physics = 0,
    double max_impact_magnitude = 0.0,
    double accumulated_impact_magnitude = 0.0,
    bool in_realtime_fc = false,
    bool session_started = false,
    int32_t session = 0,
    float current_pit_speed_limit = 0.0f) {
  ExtendedStateBuilder builder_(_fbb);
  builder_.add_accumulated_impact_magnitude(accumulated_impact_magnitude);
  builder_.add_max_impact_magnitude(max_impact_magnitude);
  builder_.add_current_pit_speed_limit(current_pit_speed_limit);
  builder_.add_session(session);
  builder_.add_physics(physics);
  builder_.add_session_started(session_started);
  builder_.add_in_realtime_fc(in_realtime_fc);
  return builder_.Finish();
}

::flatbuffers::Offset<ExtendedState> CreateExtendedState(::flatbuffers::FlatBufferBuilder &_fbb, const ExtendedStateT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline PhysicsOptionsT *PhysicsOptions::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<PhysicsOptionsT>(new PhysicsOptionsT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void PhysicsOptions::UnPackTo(PhysicsOptionsT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = traction_control(); _o->traction_control = _e; }
  { auto _e = anti_lock_brakes(); _o->anti_lock_brakes = _e; }
  { auto _e = stability_control(); _o->stability_control = _e; }
  { auto _e = auto_shift(); _o->auto_shift = _e; }
  { auto _e = auto_clutch(); _o->auto_clutch = _e; }
  { auto _e = invulnerable(); _o->invulnerable = _e; }
  { auto _e = opposite_lock(); _o->opposite_lock = _e; }
  { auto _e = steering_help(); _o->steering_help = _e; }
  { auto _e = braking_help(); _o->braking_help = _e; }
  { auto _e = spin_recovery(); _o->spin_recovery = _e; }
  { auto _e = auto_pit(); _o->auto_pit = _e; }
  { auto _e = auto_lift(); _o->auto_lift = _e; }
  { auto _e = auto_blip(); _o->auto_blip = _e; }
  { auto _e = fuel_mult(); _o->fuel_mult = _e; }
  { auto _e = tire_mult(); _o->tire_mult = _e; }
  { auto _e = mech_fail(); _o->mech_fail = _e; }
  { auto _e = allow_pitcrew_push(); _o->allow_pitcrew_push = _e; }
  { auto _e = repeat_shifts(); _o->repeat_shifts = _e; }
  { auto _e = hold_clutch(); _o->hold_clutch = _e; }
  { auto _e = auto_reverse(); _o->auto_reverse = _e; }
  { auto _e = alternate_neutral(); _o->alternate_neutral = _e; }
  { auto _e = ai_control(); _o->ai_control = _e; }
  { auto _e = manual_shift_override_time(); _o->manual_shift_override_time = _e; }
  { auto _e = auto_shift_override_time(); _o->auto_shift_override_time = _e; }
  { auto _e = speed_sensitive_steering(); _o->speed_sensitive_steering = _e; }
  { auto _e = steer_ratio_speed(); _o->steer_ratio_speed = _e; }
}

inline ::flatbuffers::Offset<PhysicsOptions> PhysicsOptions::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const PhysicsOptionsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreatePhysicsOptions(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<PhysicsOptions> CreatePhysicsOptions(::flatbuffers::FlatBufferBuilder &_fbb, const PhysicsOptionsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const PhysicsOptionsT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _traction_control = _o->traction_control;
  auto _anti_lock_brakes = _o->anti_lock_brakes;
  auto _stability_control = _o->stability_control;
  auto _auto_shift = _o->auto_shift;
  auto _auto_clutch = _o->auto_clutch;
  auto _invulnerable = _o->invulnerable;
  auto _opposite_lock = _o->opposite_lock;
  auto _steering_help = _o->steering_help;
  auto _braking_help = _o->braking_help;
  auto _spin_recovery = _o->spin_recovery;
  auto _auto_pit = _o->auto_pit;
  auto _auto_lift = _o->auto_lift;
  auto _auto_blip = _o->auto_blip;
  auto _fuel_mult = _o->fuel_mult;
  auto _tire_mult = _o->tire_mult;
  auto _mech_fail = _o->mech_fail;
  auto _allow_pitcrew_push = _o->allow_pitcrew_push;
  auto _repeat_shifts = _o->repeat_shifts;
  auto _hold_clutch = _o->hold_clutch;
  auto _auto_reverse = _o->auto_reverse;
  auto _alternate_neutral = _o->alternate_neutral;
  auto _ai_control = _o->ai_control;
  auto _manual_shift_override_time = _o->manual_shift_override_time;
  auto _auto_shift_override_time = _o->auto_shift_override_time;
  auto _speed_sensitive_steering = _o->speed_sensitive_steering;
  auto _steer_ratio_speed = _o->steer_ratio_speed;
  return isimotor::fbs::CreatePhysicsOptions(
      _fbb,
      _traction_control,
      _anti_lock_brakes,
      _stability_control,
      _auto_shift,
      _auto_clutch,
      _invulnerable,
      _opposite_lock,
      _steering_help,
      _braking_help,
      _spin_recovery,
      _auto_pit,
      _auto_lift,
      _auto_blip,
      _fuel_mult,
      _tire_mult,
      _mech_fail,
      _allow_pitcrew_push,
      _repeat_shifts,
      _hold_clutch,
      _auto_reverse,
      _alternate_neutral,
      _ai_control,
      _manual_shift_override_time,
      _auto_shift_override_time,
      _speed_sensitive_steering,
      _steer_ratio_speed);
}

inline ExtendedStateT::ExtendedStateT(const ExtendedStateT &o)
      : physics((o.physics) ? new isimotor::fbs::PhysicsOptionsT(*o.physics) : nullptr),
        max_impact_magnitude(o.max_impact_magnitude),
        accumulated_impact_magnitude(o.accumulated_impact_magnitude),
        in_realtime_fc(o.in_realtime_fc),
        session_started(o.session_started),
        session(o.session),
        current_pit_speed_limit(o.current_pit_speed_limit) {
}

inline ExtendedStateT &ExtendedStateT::operator=(ExtendedStateT o) FLATBUFFERS_NOEXCEPT {
  std::swap(physics, o.physics);
  std::swap(max_impact_magnitude, o.max_impact_magnitude);
  std::swap(accumulated_impact_magnitude, o.accumulated_impact_magnitude);
  std::swap(in_realtime_fc, o.in_realtime_fc);
  std::swap(session_started, o.session_started);
  std::swap(session, o.session);
  std::swap(current_pit_speed_limit, o.current_pit_speed_limit);
  return *this;
}

inline ExtendedStateT *ExtendedState::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ExtendedStateT>(new ExtendedStateT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ExtendedState::UnPackTo(ExtendedStateT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = physics(); if (_e) { if(_o->physics) { _e->UnPackTo(_o->physics.get(), _resolver); } else { _o->physics = std::unique_ptr<isimotor::fbs::PhysicsOptionsT>(_e->UnPack(_resolver)); } } else if (_o->physics) { _o->physics.reset(); } }
  { auto _e = max_impact_magnitude(); _o->max_impact_magnitude = _e; }
  { auto _e = accumulated_impact_magnitude(); _o->accumulated_impact_magnitude = _e; }
  { auto _e = in_realtime_fc(); _o->in_realtime_fc = _e; }
  { auto _e = session_started(); _o->session_started = _e; }
  { auto _e = session(); _o->session = _e; }
  { auto _e = current_pit_speed_limit(); _o->current_pit_speed_limit = _e; }
}

inline ::flatbuffers::Offset<ExtendedState> ExtendedState::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ExtendedStateT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateExtendedState(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ExtendedState> CreateExtendedState(::flatbuffers::FlatBufferBuilder &_fbb, const ExtendedStateT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ExtendedStateT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _physics = _o->physics ? CreatePhysicsOptions(_fbb, _o->physics.get(), _rehasher) : 0;
  auto _max_impact_magnitude = _o->max_impact_magnitude;
  auto _accumulated_impact_magnitude = _o->accumulated_impact_magnitude;
  auto _in_realtime_fc = _o->in_realtime_fc;
  auto _session_started = _o->session_started;
  auto _session = _o->session;
  auto _current_pit_speed_limit = _o->current_pit_speed_limit;
  return isimotor::fbs::CreateExtendedState(
      _fbb,
      _physics,
      _max_impact_magnitude,
      _accumulated_impact_magnitude,
      _in_realtime_fc,
      _session_started,
      _session,
      _current_pit_speed_limit);
}

inline const isimotor::fbs::ExtendedState *GetExtendedState(const void *buf) {
  return ::flatbuffers::GetRoot<isimotor::fbs::ExtendedState>(buf);
}

inline const isimotor::fbs::ExtendedState *GetSizePrefixedExtendedState(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<isimotor::fbs::ExtendedState>(buf);
}

inline bool VerifyExtendedStateBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<isimotor::fbs::ExtendedState>(nullptr);
}

inline bool VerifySizePrefixedExtendedStateBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<isimotor::fbs::ExtendedState>(nullptr);
}

inline void FinishExtendedStateBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<isimotor::fbs::ExtendedState> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedExtendedStateBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<isimotor::fbs::ExtendedState> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<isimotor::fbs::ExtendedStateT> UnPackExtendedState(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<isimotor::fbs::ExtendedStateT>(GetExtendedState(buf)->UnPack(res));
}

inline std::unique_ptr<isimotor::fbs::ExtendedStateT> UnPackSizePrefixedExtendedState(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<isimotor::fbs::ExtendedStateT>(GetSizePrefixedExtendedState(buf)->UnPack(res));
}

}  // namespace fbs
}  // namespace isimotor

#endif  // FLATBUFFERS_GENERATED_EXTENDEDSTATE_ISIMOTOR_FBS_H_
