// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FORCEFEEDBACK_ISIMOTOR_FBS_H_
#define FLATBUFFERS_GENERATED_FORCEFEEDBACK_ISIMOTOR_FBS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

namespace isimotor {
namespace fbs {

struct ForceFeedback;
struct ForceFeedbackBuilder;
struct ForceFeedbackT;

struct ForceFeedbackT : public ::flatbuffers::NativeTable {
  typedef ForceFeedback TableType;
  double force_value = 0.0;
};

struct ForceFeedback FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ForceFeedbackT NativeTableType;
  typedef ForceFeedbackBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FORCE_VALUE = 4
  };
  double force_value() const {
    return GetField<double>(VT_FORCE_VALUE, 0.0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<double>(verifier, VT_FORCE_VALUE, 8) &&
           verifier.EndTable();
  }
  ForceFeedbackT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ForceFeedbackT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ForceFeedback> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ForceFeedbackT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ForceFeedbackBuilder {
  typedef ForceFeedback Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_force_value(double force_value) {
    fbb_.AddElement<double>(ForceFeedback::VT_FORCE_VALUE, force_value, 0.0);
  }
  explicit ForceFeedbackBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ForceFeedback> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ForceFeedback>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ForceFeedback> CreateForceFeedback(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double force_value = 0.0) {
  ForceFeedbackBuilder builder_(_fbb);
  builder_.add_force_value(force_value);
  return builder_.Finish();
}

::flatbuffers::Offset<ForceFeedback> CreateForceFeedback(::flatbuffers::FlatBufferBuilder &_fbb, const ForceFeedbackT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline ForceFeedbackT *ForceFeedback::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ForceFeedbackT>(new ForceFeedbackT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ForceFeedback::UnPackTo(ForceFeedbackT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = force_value(); _o->force_value = _e; }
}

inline ::flatbuffers::Offset<ForceFeedback> ForceFeedback::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ForceFeedbackT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateForceFeedback(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ForceFeedback> CreateForceFeedback(::flatbuffers::FlatBufferBuilder &_fbb, const ForceFeedbackT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ForceFeedbackT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _force_value = _o->force_value;
  return isimotor::fbs::CreateForceFeedback(
      _fbb,
      _force_value);
}

inline const isimotor::fbs::ForceFeedback *GetForceFeedback(const void *buf) {
  return ::flatbuffers::GetRoot<isimotor::fbs::ForceFeedback>(buf);
}

inline const isimotor::fbs::ForceFeedback *GetSizePrefixedForceFeedback(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<isimotor::fbs::ForceFeedback>(buf);
}

inline bool VerifyForceFeedbackBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<isimotor::fbs::ForceFeedback>(nullptr);
}

inline bool VerifySizePrefixedForceFeedbackBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<isimotor::fbs::ForceFeedback>(nullptr);
}

inline void FinishForceFeedbackBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<isimotor::fbs::ForceFeedback> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedForceFeedbackBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<isimotor::fbs::ForceFeedback> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<isimotor::fbs::ForceFeedbackT> UnPackForceFeedback(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<isimotor::fbs::ForceFeedbackT>(GetForceFeedback(buf)->UnPack(res));
}

inline std::unique_ptr<isimotor::fbs::ForceFeedbackT> UnPackSizePrefixedForceFeedback(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<isimotor::fbs::ForceFeedbackT>(GetSizePrefixedForceFeedback(buf)->UnPack(res));
}

}  // namespace fbs
}  // namespace isimotor

#endif  // FLATBUFFERS_GENERATED_FORCEFEEDBACK_ISIMOTOR_FBS_H_
