// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_GRAPHICS_ISIMOTOR_FBS_H_
#define FLATBUFFERS_GENERATED_GRAPHICS_ISIMOTOR_FBS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

namespace isimotor {
namespace fbs {

struct Vec3;

struct Graphics;
struct GraphicsBuilder;
struct GraphicsT;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) Vec3 FLATBUFFERS_FINAL_CLASS {
 private:
  double x_;
  double y_;
  double z_;

 public:
  Vec3()
      : x_(0),
        y_(0),
        z_(0) {
  }
  Vec3(double _x, double _y, double _z)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)) {
  }
  double x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  double y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  double z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Vec3, 24);

struct GraphicsT : public ::flatbuffers::NativeTable {
  typedef Graphics TableType;
  std::unique_ptr<isimotor::fbs::Vec3> cam_pos{};
  std::unique_ptr<isimotor::fbs::Vec3> cam_ori_0{};
  std::unique_ptr<isimotor::fbs::Vec3> cam_ori_1{};
  std::unique_ptr<isimotor::fbs::Vec3> cam_ori_2{};
  double ambient_red = 0.0;
  double ambient_green = 0.0;
  double ambient_blue = 0.0;
  int32_t slot_id = 0;
  int32_t camera_type = 0;
  GraphicsT() = default;
  GraphicsT(const GraphicsT &o);
  GraphicsT(GraphicsT&&) FLATBUFFERS_NOEXCEPT = default;
  GraphicsT &operator=(GraphicsT o) FLATBUFFERS_NOEXCEPT;
};

struct Graphics FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef GraphicsT NativeTableType;
  typedef GraphicsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CAM_POS = 4,
    VT_CAM_ORI_0 = 6,
    VT_CAM_ORI_1 = 8,
    VT_CAM_ORI_2 = 10,
    VT_AMBIENT_RED = 12,
    VT_AMBIENT_GREEN = 14,
    VT_AMBIENT_BLUE = 16,
    VT_SLOT_ID = 18,
    VT_CAMERA_TYPE = 20
  };
  const isimotor::fbs::Vec3 *cam_pos() const {
    return GetStruct<const isimotor::fbs::Vec3 *>(VT_CAM_POS);
  }
  const isimotor::fbs::Vec3 *cam_ori_0() const {
    return GetStruct<const isimotor::fbs::Vec3 *>(VT_CAM_ORI_0);
  }
  const isimotor::fbs::Vec3 *cam_ori_1() const {
    return GetStruct<const isimotor::fbs::Vec3 *>(VT_CAM_ORI_1);
  }
  const isimotor::fbs::Vec3 *cam_ori_2() const {
    return GetStruct<const isimotor::fbs::Vec3 *>(VT_CAM_ORI_2);
  }
  double ambient_red() const {
    return GetField<double>(VT_AMBIENT_RED, 0.0);
  }
  double ambient_green() const {
    return GetField<double>(VT_AMBIENT_GREEN, 0.0);
  }
  double ambient_blue() const {
    return GetField<double>(VT_AMBIENT_BLUE, 0.0);
  }
  int32_t slot_id() const {
    return GetField<int32_t>(VT_SLOT_ID, 0);
  }
  int32_t camera_type() const {
    return GetField<int32_t>(VT_CAMERA_TYPE, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<isimotor::fbs::Vec3>(verifier, VT_CAM_POS, 8) &&
           VerifyField<isimotor::fbs::Vec3>(verifier, VT_CAM_ORI_0, 8) &&
           VerifyField<isimotor::fbs::Vec3>(verifier, VT_CAM_ORI_1, 8) &&
           VerifyField<isimotor::fbs::Vec3>(verifier, VT_CAM_ORI_2, 8) &&
           VerifyField<double>(verifier, VT_AMBIENT_RED, 8) &&
           VerifyField<double>(verifier, VT_AMBIENT_GREEN, 8) &&
           VerifyField<double>(verifier, VT_AMBIENT_BLUE, 8) &&
           VerifyField<int32_t>(verifier, VT_SLOT_ID, 4) &&
           VerifyField<int32_t>(verifier, VT_CAMERA_TYPE, 4) &&
           verifier.EndTable();
  }
  GraphicsT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(GraphicsT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Graphics> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const GraphicsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct GraphicsBuilder {
  typedef Graphics Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_cam_pos(const isimotor::fbs::Vec3 *cam_pos) {
    fbb_.AddStruct(Graphics::VT_CAM_POS, cam_pos);
  }
  void add_cam_ori_0(const isimotor::fbs::Vec3 *cam_ori_0) {
    fbb_.AddStruct(Graphics::VT_CAM_ORI_0, cam_ori_0);
  }
  void add_cam_ori_1(const isimotor::fbs::Vec3 *cam_ori_1) {
    fbb_.AddStruct(Graphics::VT_CAM_ORI_1, cam_ori_1);
  }
  void add_cam_ori_2(const isimotor::fbs::Vec3 *cam_ori_2) {
    fbb_.AddStruct(Graphics::VT_CAM_ORI_2, cam_ori_2);
  }
  void add_ambient_red(double ambient_red) {
    fbb_.AddElement<double>(Graphics::VT_AMBIENT_RED, ambient_red, 0.0);
  }
  void add_ambient_green(double ambient_green) {
    fbb_.AddElement<double>(Graphics::VT_AMBIENT_GREEN, ambient_green, 0.0);
  }
  void add_ambient_blue(double ambient_blue) {
    fbb_.AddElement<double>(Graphics::VT_AMBIENT_BLUE, ambient_blue, 0.0);
  }
  void add_slot_id(int32_t slot_id) {
    fbb_.AddElement<int32_t>(Graphics::VT_SLOT_ID, slot_id, 0);
  }
  void add_camera_type(int32_t camera_type) {
    fbb_.AddElement<int32_t>(Graphics::VT_CAMERA_TYPE, camera_type, 0);
  }
  explicit GraphicsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Graphics> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Graphics>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Graphics> CreateGraphics(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const isimotor::fbs::Vec3 *cam_pos = nullptr,
    const isimotor::fbs::Vec3 *cam_ori_0 = nullptr,
    const isimotor::fbs::Vec3 *cam_ori_1 = nullptr,
    const isimotor::fbs::Vec3 *cam_ori_2 = nullptr,
    double ambient_red = 0.0,
    double ambient_green = 0.0,
    double ambient_blue = 0.0,
    int32_t slot_id = 0,
    int32_t camera_type = 0) {
  GraphicsBuilder builder_(_fbb);
  builder_.add_ambient_blue(ambient_blue);
  builder_.add_ambient_green(ambient_green);
  builder_.add_ambient_red(ambient_red);
  builder_.add_camera_type(camera_type);
  builder_.add_slot_id(slot_id);
  builder_.add_cam_ori_2(cam_ori_2);
  builder_.add_cam_ori_1(cam_ori_1);
  builder_.add_cam_ori_0(cam_ori_0);
  builder_.add_cam_pos(cam_pos);
  return builder_.Finish();
}

::flatbuffers::Offset<Graphics> CreateGraphics(::flatbuffers::FlatBufferBuilder &_fbb, const GraphicsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline GraphicsT::GraphicsT(const GraphicsT &o)
      : cam_pos((o.cam_pos) ? new isimotor::fbs::Vec3(*o.cam_pos) : nullptr),
        cam_ori_0((o.cam_ori_0) ? new isimotor::fbs::Vec3(*o.cam_ori_0) : nullptr),
        cam_ori_1((o.cam_ori_1) ? new isimotor::fbs::Vec3(*o.cam_ori_1) : nullptr),
        cam_ori_2((o.cam_ori_2) ? new isimotor::fbs::Vec3(*o.cam_ori_2) : nullptr),
        ambient_red(o.ambient_red),
        ambient_green(o.ambient_green),
        ambient_blue(o.ambient_blue),
        slot_id(o.slot_id),
        camera_type(o.camera_type) {
}

inline GraphicsT &GraphicsT::operator=(GraphicsT o) FLATBUFFERS_NOEXCEPT {
  std::swap(cam_pos, o.cam_pos);
  std::swap(cam_ori_0, o.cam_ori_0);
  std::swap(cam_ori_1, o.cam_ori_1);
  std::swap(cam_ori_2, o.cam_ori_2);
  std::swap(ambient_red, o.ambient_red);
  std::swap(ambient_green, o.ambient_green);
  std::swap(ambient_blue, o.ambient_blue);
  std::swap(slot_id, o.slot_id);
  std::swap(camera_type, o.camera_type);
  return *this;
}

inline GraphicsT *Graphics::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<GraphicsT>(new GraphicsT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Graphics::UnPackTo(GraphicsT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = cam_pos(); if (_e) _o->cam_pos = std::unique_ptr<isimotor::fbs::Vec3>(new isimotor::fbs::Vec3(*_e)); }
  { auto _e = cam_ori_0(); if (_e) _o->cam_ori_0 = std::unique_ptr<isimotor::fbs::Vec3>(new isimotor::fbs::Vec3(*_e)); }
  { auto _e = cam_ori_1(); if (_e) _o->cam_ori_1 = std::unique_ptr<isimotor::fbs::Vec3>(new isimotor::fbs::Vec3(*_e)); }
  { auto _e = cam_ori_2(); if (_e) _o->cam_ori_2 = std::unique_ptr<isimotor::fbs::Vec3>(new isimotor::fbs::Vec3(*_e)); }
  { auto _e = ambient_red(); _o->ambient_red = _e; }
  { auto _e = ambient_green(); _o->ambient_green = _e; }
  { auto _e = ambient_blue(); _o->ambient_blue = _e; }
  { auto _e = slot_id(); _o->slot_id = _e; }
  { auto _e = camera_type(); _o->camera_type = _e; }
}

inline ::flatbuffers::Offset<Graphics> Graphics::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const GraphicsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateGraphics(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Graphics> CreateGraphics(::flatbuffers::FlatBufferBuilder &_fbb, const GraphicsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const GraphicsT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _cam_pos = _o->cam_pos ? _o->cam_pos.get() : nullptr;
  auto _cam_ori_0 = _o->cam_ori_0 ? _o->cam_ori_0.get() : nullptr;
  auto _cam_ori_1 = _o->cam_ori_1 ? _o->cam_ori_1.get() : nullptr;
  auto _cam_ori_2 = _o->cam_ori_2 ? _o->cam_ori_2.get() : nullptr;
  auto _ambient_red = _o->ambient_red;
  auto _ambient_green = _o->ambient_green;
  auto _ambient_blue = _o->ambient_blue;
  auto _slot_id = _o->slot_id;
  auto _camera_type = _o->camera_type;
  return isimotor::fbs::CreateGraphics(
      _fbb,
      _cam_pos,
      _cam_ori_0,
      _cam_ori_1,
      _cam_ori_2,
      _ambient_red,
      _ambient_green,
      _ambient_blue,
      _slot_id,
      _camera_type);
}

inline const isimotor::fbs::Graphics *GetGraphics(const void *buf) {
  return ::flatbuffers::GetRoot<isimotor::fbs::Graphics>(buf);
}

inline const isimotor::fbs::Graphics *GetSizePrefixedGraphics(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<isimotor::fbs::Graphics>(buf);
}

inline bool VerifyGraphicsBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<isimotor::fbs::Graphics>(nullptr);
}

inline bool VerifySizePrefixedGraphicsBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<isimotor::fbs::Graphics>(nullptr);
}

inline void FinishGraphicsBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<isimotor::fbs::Graphics> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedGraphicsBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<isimotor::fbs::Graphics> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<isimotor::fbs::GraphicsT> UnPackGraphics(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<isimotor::fbs::GraphicsT>(GetGraphics(buf)->UnPack(res));
}

inline std::unique_ptr<isimotor::fbs::GraphicsT> UnPackSizePrefixedGraphics(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<isimotor::fbs::GraphicsT>(GetSizePrefixedGraphics(buf)->UnPack(res));
}

}  // namespace fbs
}  // namespace isimotor

#endif  // FLATBUFFERS_GENERATED_GRAPHICS_ISIMOTOR_FBS_H_
