// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SYSTEMEVENT_ISIMOTOR_FBS_H_
#define FLATBUFFERS_GENERATED_SYSTEMEVENT_ISIMOTOR_FBS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

namespace isimotor {
namespace fbs {

struct SystemEvent;
struct SystemEventBuilder;
struct SystemEventT;

struct SystemEventT : public ::flatbuffers::NativeTable {
  typedef SystemEvent TableType;
  uint8_t event_type = 0;
};

struct SystemEvent FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SystemEventT NativeTableType;
  typedef SystemEventBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_EVENT_TYPE = 4
  };
  uint8_t event_type() const {
    return GetField<uint8_t>(VT_EVENT_TYPE, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_EVENT_TYPE, 1) &&
           verifier.EndTable();
  }
  SystemEventT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(SystemEventT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<SystemEvent> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SystemEventT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct SystemEventBuilder {
  typedef SystemEvent Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_event_type(uint8_t event_type) {
    fbb_.AddElement<uint8_t>(SystemEvent::VT_EVENT_TYPE, event_type, 0);
  }
  explicit SystemEventBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SystemEvent> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SystemEvent>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SystemEvent> CreateSystemEvent(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t event_type = 0) {
  SystemEventBuilder builder_(_fbb);
  builder_.add_event_type(event_type);
  return builder_.Finish();
}

::flatbuffers::Offset<SystemEvent> CreateSystemEvent(::flatbuffers::FlatBufferBuilder &_fbb, const SystemEventT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline SystemEventT *SystemEvent::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<SystemEventT>(new SystemEventT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void SystemEvent::UnPackTo(SystemEventT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = event_type(); _o->event_type = _e; }
}

inline ::flatbuffers::Offset<SystemEvent> SystemEvent::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SystemEventT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateSystemEvent(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<SystemEvent> CreateSystemEvent(::flatbuffers::FlatBufferBuilder &_fbb, const SystemEventT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const SystemEventT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _event_type = _o->event_type;
  return isimotor::fbs::CreateSystemEvent(
      _fbb,
      _event_type);
}

inline const isimotor::fbs::SystemEvent *GetSystemEvent(const void *buf) {
  return ::flatbuffers::GetRoot<isimotor::fbs::SystemEvent>(buf);
}

inline const isimotor::fbs::SystemEvent *GetSizePrefixedSystemEvent(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<isimotor::fbs::SystemEvent>(buf);
}

inline bool VerifySystemEventBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<isimotor::fbs::SystemEvent>(nullptr);
}

inline bool VerifySizePrefixedSystemEventBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<isimotor::fbs::SystemEvent>(nullptr);
}

inline void FinishSystemEventBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<isimotor::fbs::SystemEvent> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedSystemEventBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<isimotor::fbs::SystemEvent> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<isimotor::fbs::SystemEventT> UnPackSystemEvent(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<isimotor::fbs::SystemEventT>(GetSystemEvent(buf)->UnPack(res));
}

inline std::unique_ptr<isimotor::fbs::SystemEventT> UnPackSizePrefixedSystemEvent(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<isimotor::fbs::SystemEventT>(GetSizePrefixedSystemEvent(buf)->UnPack(res));
}

}  // namespace fbs
}  // namespace isimotor

#endif  // FLATBUFFERS_GENERATED_SYSTEMEVENT_ISIMOTOR_FBS_H_
