# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CompactScoring(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CompactScoring()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCompactScoring(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CompactScoring
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CompactScoring
    def TrackName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CompactScoring
    def Session(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CompactScoring
    def CurrentEt(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # CompactScoring
    def TotalLapDist(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # CompactScoring
    def MaxLaps(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CompactScoring
    def InRealtime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # CompactScoring
    def TotalLaps(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int16Flags, o + self._tab.Pos)
        return 0

    # CompactScoring
    def Sector(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # CompactScoring
    def InGarageStall(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # CompactScoring
    def CountLapFlag(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # CompactScoring
    def CurSector1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # CompactScoring
    def CurSector2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # CompactScoring
    def LastSector1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # CompactScoring
    def LastSector2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # CompactScoring
    def LastLapTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # CompactScoring
    def BestSector1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # CompactScoring
    def BestSector2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # CompactScoring
    def BestLapTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def CompactScoringStart(builder):
    builder.StartObject(18)

def Start(builder):
    CompactScoringStart(builder)

def CompactScoringAddTrackName(builder, trackName):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(trackName), 0)

def AddTrackName(builder, trackName):
    CompactScoringAddTrackName(builder, trackName)

def CompactScoringAddSession(builder, session):
    builder.PrependInt32Slot(1, session, 0)

def AddSession(builder, session):
    CompactScoringAddSession(builder, session)

def CompactScoringAddCurrentEt(builder, currentEt):
    builder.PrependFloat64Slot(2, currentEt, 0.0)

def AddCurrentEt(builder, currentEt):
    CompactScoringAddCurrentEt(builder, currentEt)

def CompactScoringAddTotalLapDist(builder, totalLapDist):
    builder.PrependFloat64Slot(3, totalLapDist, 0.0)

def AddTotalLapDist(builder, totalLapDist):
    CompactScoringAddTotalLapDist(builder, totalLapDist)

def CompactScoringAddMaxLaps(builder, maxLaps):
    builder.PrependInt32Slot(4, maxLaps, 0)

def AddMaxLaps(builder, maxLaps):
    CompactScoringAddMaxLaps(builder, maxLaps)

def CompactScoringAddInRealtime(builder, inRealtime):
    builder.PrependBoolSlot(5, inRealtime, 0)

def AddInRealtime(builder, inRealtime):
    CompactScoringAddInRealtime(builder, inRealtime)

def CompactScoringAddTotalLaps(builder, totalLaps):
    builder.PrependInt16Slot(6, totalLaps, 0)

def AddTotalLaps(builder, totalLaps):
    CompactScoringAddTotalLaps(builder, totalLaps)

def CompactScoringAddSector(builder, sector):
    builder.PrependInt8Slot(7, sector, 0)

def AddSector(builder, sector):
    CompactScoringAddSector(builder, sector)

def CompactScoringAddInGarageStall(builder, inGarageStall):
    builder.PrependBoolSlot(8, inGarageStall, 0)

def AddInGarageStall(builder, inGarageStall):
    CompactScoringAddInGarageStall(builder, inGarageStall)

def CompactScoringAddCountLapFlag(builder, countLapFlag):
    builder.PrependUint8Slot(9, countLapFlag, 0)

def AddCountLapFlag(builder, countLapFlag):
    CompactScoringAddCountLapFlag(builder, countLapFlag)

def CompactScoringAddCurSector1(builder, curSector1):
    builder.PrependFloat64Slot(10, curSector1, 0.0)

def AddCurSector1(builder, curSector1):
    CompactScoringAddCurSector1(builder, curSector1)

def CompactScoringAddCurSector2(builder, curSector2):
    builder.PrependFloat64Slot(11, curSector2, 0.0)

def AddCurSector2(builder, curSector2):
    CompactScoringAddCurSector2(builder, curSector2)

def CompactScoringAddLastSector1(builder, lastSector1):
    builder.PrependFloat64Slot(12, lastSector1, 0.0)

def AddLastSector1(builder, lastSector1):
    CompactScoringAddLastSector1(builder, lastSector1)

def CompactScoringAddLastSector2(builder, lastSector2):
    builder.PrependFloat64Slot(13, lastSector2, 0.0)

def AddLastSector2(builder, lastSector2):
    CompactScoringAddLastSector2(builder, lastSector2)

def CompactScoringAddLastLapTime(builder, lastLapTime):
    builder.PrependFloat64Slot(14, lastLapTime, 0.0)

def AddLastLapTime(builder, lastLapTime):
    CompactScoringAddLastLapTime(builder, lastLapTime)

def CompactScoringAddBestSector1(builder, bestSector1):
    builder.PrependFloat64Slot(15, bestSector1, 0.0)

def AddBestSector1(builder, bestSector1):
    CompactScoringAddBestSector1(builder, bestSector1)

def CompactScoringAddBestSector2(builder, bestSector2):
    builder.PrependFloat64Slot(16, bestSector2, 0.0)

def AddBestSector2(builder, bestSector2):
    CompactScoringAddBestSector2(builder, bestSector2)

def CompactScoringAddBestLapTime(builder, bestLapTime):
    builder.PrependFloat64Slot(17, bestLapTime, 0.0)

def AddBestLapTime(builder, bestLapTime):
    CompactScoringAddBestLapTime(builder, bestLapTime)

def CompactScoringEnd(builder):
    return builder.EndObject()

def End(builder):
    return CompactScoringEnd(builder)
