# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class InboundCommand(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = InboundCommand()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsInboundCommand(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # InboundCommand
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # InboundCommand
    def PayloadType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # InboundCommand
    def Payload(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def InboundCommandStart(builder):
    builder.StartObject(2)

def Start(builder):
    InboundCommandStart(builder)

def InboundCommandAddPayloadType(builder, payloadType):
    builder.PrependUint8Slot(0, payloadType, 0)

def AddPayloadType(builder, payloadType):
    InboundCommandAddPayloadType(builder, payloadType)

def InboundCommandAddPayload(builder, payload):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(payload), 0)

def AddPayload(builder, payload):
    InboundCommandAddPayload(builder, payload)

def InboundCommandEnd(builder):
    return builder.EndObject()

def End(builder):
    return InboundCommandEnd(builder)
