# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SystemEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SystemEvent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSystemEvent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SystemEvent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SystemEvent
    def EventType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def SystemEventStart(builder):
    builder.StartObject(1)

def Start(builder):
    SystemEventStart(builder)

def SystemEventAddEventType(builder, eventType):
    builder.PrependUint8Slot(0, eventType, 0)

def AddEventType(builder, eventType):
    SystemEventAddEventType(builder, eventType)

def SystemEventEnd(builder):
    return builder.EndObject()

def End(builder):
    return SystemEventEnd(builder)
