# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class VehicleScoring(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VehicleScoring()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVehicleScoring(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # VehicleScoring
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VehicleScoring
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # VehicleScoring
    def DriverName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # VehicleScoring
    def VehicleName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # VehicleScoring
    def TotalLaps(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int16Flags, o + self._tab.Pos)
        return 0

    # VehicleScoring
    def Sector(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # VehicleScoring
    def FinishStatus(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # VehicleScoring
    def VehicleLapDist(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # VehicleScoring
    def PathLateral(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # VehicleScoring
    def TrackEdge(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # VehicleScoring
    def BestSector1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # VehicleScoring
    def BestSector2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # VehicleScoring
    def BestLapTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # VehicleScoring
    def LastSector1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # VehicleScoring
    def LastSector2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # VehicleScoring
    def LastLapTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # VehicleScoring
    def CurSector1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # VehicleScoring
    def CurSector2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # VehicleScoring
    def NumPitstops(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int16Flags, o + self._tab.Pos)
        return 0

    # VehicleScoring
    def NumPenalties(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int16Flags, o + self._tab.Pos)
        return 0

    # VehicleScoring
    def IsPlayer(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # VehicleScoring
    def Control(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # VehicleScoring
    def InPits(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # VehicleScoring
    def Place(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(48))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # VehicleScoring
    def VehicleClass(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(50))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # VehicleScoring
    def TimeBehindNext(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # VehicleScoring
    def LapsBehindNext(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(54))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # VehicleScoring
    def TimeBehindLeader(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(56))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # VehicleScoring
    def LapsBehindLeader(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(58))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # VehicleScoring
    def LapStartEt(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(60))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # VehicleScoring
    def Pos(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(62))
        if o != 0:
            x = o + self._tab.Pos
            from isimotor_pulse_types.fbs_generated.isimotor.fbs.Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # VehicleScoring
    def LocalVel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(64))
        if o != 0:
            x = o + self._tab.Pos
            from isimotor_pulse_types.fbs_generated.isimotor.fbs.Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # VehicleScoring
    def LocalAccel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(66))
        if o != 0:
            x = o + self._tab.Pos
            from isimotor_pulse_types.fbs_generated.isimotor.fbs.Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # VehicleScoring
    def Ori0(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(68))
        if o != 0:
            x = o + self._tab.Pos
            from isimotor_pulse_types.fbs_generated.isimotor.fbs.Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # VehicleScoring
    def Ori1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(70))
        if o != 0:
            x = o + self._tab.Pos
            from isimotor_pulse_types.fbs_generated.isimotor.fbs.Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # VehicleScoring
    def Ori2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(72))
        if o != 0:
            x = o + self._tab.Pos
            from isimotor_pulse_types.fbs_generated.isimotor.fbs.Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # VehicleScoring
    def LocalRot(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(74))
        if o != 0:
            x = o + self._tab.Pos
            from isimotor_pulse_types.fbs_generated.isimotor.fbs.Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # VehicleScoring
    def LocalRotAccel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(76))
        if o != 0:
            x = o + self._tab.Pos
            from isimotor_pulse_types.fbs_generated.isimotor.fbs.Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # VehicleScoring
    def Headlights(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(78))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # VehicleScoring
    def PitState(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(80))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # VehicleScoring
    def ServerScored(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(82))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # VehicleScoring
    def IndividualPhase(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(84))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # VehicleScoring
    def Qualification(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(86))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # VehicleScoring
    def TimeIntoLap(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(88))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # VehicleScoring
    def EstimatedLapTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(90))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # VehicleScoring
    def PitGroup(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(92))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # VehicleScoring
    def Flag(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(94))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # VehicleScoring
    def UnderYellow(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(96))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # VehicleScoring
    def CountLapFlag(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(98))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # VehicleScoring
    def InGarageStall(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(100))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # VehicleScoring
    def PitLapDist(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(102))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # VehicleScoring
    def BestLapSector1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(104))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # VehicleScoring
    def BestLapSector2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(106))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # VehicleScoring
    def Lmu(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(108))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from isimotor_pulse_types.fbs_generated.isimotor.fbs.LmuVehicleScoring import LmuVehicleScoring
            obj = LmuVehicleScoring()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def VehicleScoringStart(builder):
    builder.StartObject(53)

def Start(builder):
    VehicleScoringStart(builder)

def VehicleScoringAddId(builder, id):
    builder.PrependInt32Slot(0, id, 0)

def AddId(builder, id):
    VehicleScoringAddId(builder, id)

def VehicleScoringAddDriverName(builder, driverName):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(driverName), 0)

def AddDriverName(builder, driverName):
    VehicleScoringAddDriverName(builder, driverName)

def VehicleScoringAddVehicleName(builder, vehicleName):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(vehicleName), 0)

def AddVehicleName(builder, vehicleName):
    VehicleScoringAddVehicleName(builder, vehicleName)

def VehicleScoringAddTotalLaps(builder, totalLaps):
    builder.PrependInt16Slot(3, totalLaps, 0)

def AddTotalLaps(builder, totalLaps):
    VehicleScoringAddTotalLaps(builder, totalLaps)

def VehicleScoringAddSector(builder, sector):
    builder.PrependInt8Slot(4, sector, 0)

def AddSector(builder, sector):
    VehicleScoringAddSector(builder, sector)

def VehicleScoringAddFinishStatus(builder, finishStatus):
    builder.PrependInt8Slot(5, finishStatus, 0)

def AddFinishStatus(builder, finishStatus):
    VehicleScoringAddFinishStatus(builder, finishStatus)

def VehicleScoringAddVehicleLapDist(builder, vehicleLapDist):
    builder.PrependFloat64Slot(6, vehicleLapDist, 0.0)

def AddVehicleLapDist(builder, vehicleLapDist):
    VehicleScoringAddVehicleLapDist(builder, vehicleLapDist)

def VehicleScoringAddPathLateral(builder, pathLateral):
    builder.PrependFloat64Slot(7, pathLateral, 0.0)

def AddPathLateral(builder, pathLateral):
    VehicleScoringAddPathLateral(builder, pathLateral)

def VehicleScoringAddTrackEdge(builder, trackEdge):
    builder.PrependFloat64Slot(8, trackEdge, 0.0)

def AddTrackEdge(builder, trackEdge):
    VehicleScoringAddTrackEdge(builder, trackEdge)

def VehicleScoringAddBestSector1(builder, bestSector1):
    builder.PrependFloat64Slot(9, bestSector1, 0.0)

def AddBestSector1(builder, bestSector1):
    VehicleScoringAddBestSector1(builder, bestSector1)

def VehicleScoringAddBestSector2(builder, bestSector2):
    builder.PrependFloat64Slot(10, bestSector2, 0.0)

def AddBestSector2(builder, bestSector2):
    VehicleScoringAddBestSector2(builder, bestSector2)

def VehicleScoringAddBestLapTime(builder, bestLapTime):
    builder.PrependFloat64Slot(11, bestLapTime, 0.0)

def AddBestLapTime(builder, bestLapTime):
    VehicleScoringAddBestLapTime(builder, bestLapTime)

def VehicleScoringAddLastSector1(builder, lastSector1):
    builder.PrependFloat64Slot(12, lastSector1, 0.0)

def AddLastSector1(builder, lastSector1):
    VehicleScoringAddLastSector1(builder, lastSector1)

def VehicleScoringAddLastSector2(builder, lastSector2):
    builder.PrependFloat64Slot(13, lastSector2, 0.0)

def AddLastSector2(builder, lastSector2):
    VehicleScoringAddLastSector2(builder, lastSector2)

def VehicleScoringAddLastLapTime(builder, lastLapTime):
    builder.PrependFloat64Slot(14, lastLapTime, 0.0)

def AddLastLapTime(builder, lastLapTime):
    VehicleScoringAddLastLapTime(builder, lastLapTime)

def VehicleScoringAddCurSector1(builder, curSector1):
    builder.PrependFloat64Slot(15, curSector1, 0.0)

def AddCurSector1(builder, curSector1):
    VehicleScoringAddCurSector1(builder, curSector1)

def VehicleScoringAddCurSector2(builder, curSector2):
    builder.PrependFloat64Slot(16, curSector2, 0.0)

def AddCurSector2(builder, curSector2):
    VehicleScoringAddCurSector2(builder, curSector2)

def VehicleScoringAddNumPitstops(builder, numPitstops):
    builder.PrependInt16Slot(17, numPitstops, 0)

def AddNumPitstops(builder, numPitstops):
    VehicleScoringAddNumPitstops(builder, numPitstops)

def VehicleScoringAddNumPenalties(builder, numPenalties):
    builder.PrependInt16Slot(18, numPenalties, 0)

def AddNumPenalties(builder, numPenalties):
    VehicleScoringAddNumPenalties(builder, numPenalties)

def VehicleScoringAddIsPlayer(builder, isPlayer):
    builder.PrependBoolSlot(19, isPlayer, 0)

def AddIsPlayer(builder, isPlayer):
    VehicleScoringAddIsPlayer(builder, isPlayer)

def VehicleScoringAddControl(builder, control):
    builder.PrependInt8Slot(20, control, 0)

def AddControl(builder, control):
    VehicleScoringAddControl(builder, control)

def VehicleScoringAddInPits(builder, inPits):
    builder.PrependBoolSlot(21, inPits, 0)

def AddInPits(builder, inPits):
    VehicleScoringAddInPits(builder, inPits)

def VehicleScoringAddPlace(builder, place):
    builder.PrependUint8Slot(22, place, 0)

def AddPlace(builder, place):
    VehicleScoringAddPlace(builder, place)

def VehicleScoringAddVehicleClass(builder, vehicleClass):
    builder.PrependUOffsetTRelativeSlot(23, flatbuffers.number_types.UOffsetTFlags.py_type(vehicleClass), 0)

def AddVehicleClass(builder, vehicleClass):
    VehicleScoringAddVehicleClass(builder, vehicleClass)

def VehicleScoringAddTimeBehindNext(builder, timeBehindNext):
    builder.PrependFloat64Slot(24, timeBehindNext, 0.0)

def AddTimeBehindNext(builder, timeBehindNext):
    VehicleScoringAddTimeBehindNext(builder, timeBehindNext)

def VehicleScoringAddLapsBehindNext(builder, lapsBehindNext):
    builder.PrependInt32Slot(25, lapsBehindNext, 0)

def AddLapsBehindNext(builder, lapsBehindNext):
    VehicleScoringAddLapsBehindNext(builder, lapsBehindNext)

def VehicleScoringAddTimeBehindLeader(builder, timeBehindLeader):
    builder.PrependFloat64Slot(26, timeBehindLeader, 0.0)

def AddTimeBehindLeader(builder, timeBehindLeader):
    VehicleScoringAddTimeBehindLeader(builder, timeBehindLeader)

def VehicleScoringAddLapsBehindLeader(builder, lapsBehindLeader):
    builder.PrependInt32Slot(27, lapsBehindLeader, 0)

def AddLapsBehindLeader(builder, lapsBehindLeader):
    VehicleScoringAddLapsBehindLeader(builder, lapsBehindLeader)

def VehicleScoringAddLapStartEt(builder, lapStartEt):
    builder.PrependFloat64Slot(28, lapStartEt, 0.0)

def AddLapStartEt(builder, lapStartEt):
    VehicleScoringAddLapStartEt(builder, lapStartEt)

def VehicleScoringAddPos(builder, pos):
    builder.PrependStructSlot(29, flatbuffers.number_types.UOffsetTFlags.py_type(pos), 0)

def AddPos(builder, pos):
    VehicleScoringAddPos(builder, pos)

def VehicleScoringAddLocalVel(builder, localVel):
    builder.PrependStructSlot(30, flatbuffers.number_types.UOffsetTFlags.py_type(localVel), 0)

def AddLocalVel(builder, localVel):
    VehicleScoringAddLocalVel(builder, localVel)

def VehicleScoringAddLocalAccel(builder, localAccel):
    builder.PrependStructSlot(31, flatbuffers.number_types.UOffsetTFlags.py_type(localAccel), 0)

def AddLocalAccel(builder, localAccel):
    VehicleScoringAddLocalAccel(builder, localAccel)

def VehicleScoringAddOri0(builder, ori0):
    builder.PrependStructSlot(32, flatbuffers.number_types.UOffsetTFlags.py_type(ori0), 0)

def AddOri0(builder, ori0):
    VehicleScoringAddOri0(builder, ori0)

def VehicleScoringAddOri1(builder, ori1):
    builder.PrependStructSlot(33, flatbuffers.number_types.UOffsetTFlags.py_type(ori1), 0)

def AddOri1(builder, ori1):
    VehicleScoringAddOri1(builder, ori1)

def VehicleScoringAddOri2(builder, ori2):
    builder.PrependStructSlot(34, flatbuffers.number_types.UOffsetTFlags.py_type(ori2), 0)

def AddOri2(builder, ori2):
    VehicleScoringAddOri2(builder, ori2)

def VehicleScoringAddLocalRot(builder, localRot):
    builder.PrependStructSlot(35, flatbuffers.number_types.UOffsetTFlags.py_type(localRot), 0)

def AddLocalRot(builder, localRot):
    VehicleScoringAddLocalRot(builder, localRot)

def VehicleScoringAddLocalRotAccel(builder, localRotAccel):
    builder.PrependStructSlot(36, flatbuffers.number_types.UOffsetTFlags.py_type(localRotAccel), 0)

def AddLocalRotAccel(builder, localRotAccel):
    VehicleScoringAddLocalRotAccel(builder, localRotAccel)

def VehicleScoringAddHeadlights(builder, headlights):
    builder.PrependUint8Slot(37, headlights, 0)

def AddHeadlights(builder, headlights):
    VehicleScoringAddHeadlights(builder, headlights)

def VehicleScoringAddPitState(builder, pitState):
    builder.PrependUint8Slot(38, pitState, 0)

def AddPitState(builder, pitState):
    VehicleScoringAddPitState(builder, pitState)

def VehicleScoringAddServerScored(builder, serverScored):
    builder.PrependUint8Slot(39, serverScored, 0)

def AddServerScored(builder, serverScored):
    VehicleScoringAddServerScored(builder, serverScored)

def VehicleScoringAddIndividualPhase(builder, individualPhase):
    builder.PrependUint8Slot(40, individualPhase, 0)

def AddIndividualPhase(builder, individualPhase):
    VehicleScoringAddIndividualPhase(builder, individualPhase)

def VehicleScoringAddQualification(builder, qualification):
    builder.PrependInt32Slot(41, qualification, 0)

def AddQualification(builder, qualification):
    VehicleScoringAddQualification(builder, qualification)

def VehicleScoringAddTimeIntoLap(builder, timeIntoLap):
    builder.PrependFloat64Slot(42, timeIntoLap, 0.0)

def AddTimeIntoLap(builder, timeIntoLap):
    VehicleScoringAddTimeIntoLap(builder, timeIntoLap)

def VehicleScoringAddEstimatedLapTime(builder, estimatedLapTime):
    builder.PrependFloat64Slot(43, estimatedLapTime, 0.0)

def AddEstimatedLapTime(builder, estimatedLapTime):
    VehicleScoringAddEstimatedLapTime(builder, estimatedLapTime)

def VehicleScoringAddPitGroup(builder, pitGroup):
    builder.PrependUOffsetTRelativeSlot(44, flatbuffers.number_types.UOffsetTFlags.py_type(pitGroup), 0)

def AddPitGroup(builder, pitGroup):
    VehicleScoringAddPitGroup(builder, pitGroup)

def VehicleScoringAddFlag(builder, flag):
    builder.PrependUint8Slot(45, flag, 0)

def AddFlag(builder, flag):
    VehicleScoringAddFlag(builder, flag)

def VehicleScoringAddUnderYellow(builder, underYellow):
    builder.PrependBoolSlot(46, underYellow, 0)

def AddUnderYellow(builder, underYellow):
    VehicleScoringAddUnderYellow(builder, underYellow)

def VehicleScoringAddCountLapFlag(builder, countLapFlag):
    builder.PrependUint8Slot(47, countLapFlag, 0)

def AddCountLapFlag(builder, countLapFlag):
    VehicleScoringAddCountLapFlag(builder, countLapFlag)

def VehicleScoringAddInGarageStall(builder, inGarageStall):
    builder.PrependBoolSlot(48, inGarageStall, 0)

def AddInGarageStall(builder, inGarageStall):
    VehicleScoringAddInGarageStall(builder, inGarageStall)

def VehicleScoringAddPitLapDist(builder, pitLapDist):
    builder.PrependFloat32Slot(49, pitLapDist, 0.0)

def AddPitLapDist(builder, pitLapDist):
    VehicleScoringAddPitLapDist(builder, pitLapDist)

def VehicleScoringAddBestLapSector1(builder, bestLapSector1):
    builder.PrependFloat32Slot(50, bestLapSector1, 0.0)

def AddBestLapSector1(builder, bestLapSector1):
    VehicleScoringAddBestLapSector1(builder, bestLapSector1)

def VehicleScoringAddBestLapSector2(builder, bestLapSector2):
    builder.PrependFloat32Slot(51, bestLapSector2, 0.0)

def AddBestLapSector2(builder, bestLapSector2):
    VehicleScoringAddBestLapSector2(builder, bestLapSector2)

def VehicleScoringAddLmu(builder, lmu):
    builder.PrependUOffsetTRelativeSlot(52, flatbuffers.number_types.UOffsetTFlags.py_type(lmu), 0)

def AddLmu(builder, lmu):
    VehicleScoringAddLmu(builder, lmu)

def VehicleScoringEnd(builder):
    return builder.EndObject()

def End(builder):
    return VehicleScoringEnd(builder)
