# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WeatherControlCommand(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WeatherControlCommand()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWeatherControlCommand(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WeatherControlCommand
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WeatherControlCommand
    def AmbientTemp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # WeatherControlCommand
    def TrackTemp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # WeatherControlCommand
    def DarkCloud(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # WeatherControlCommand
    def Raining(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # WeatherControlCommand
    def WindSpeed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # WeatherControlCommand
    def WindDirection(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # WeatherControlCommand
    def MinPathWetness(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # WeatherControlCommand
    def MaxPathWetness(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def WeatherControlCommandStart(builder):
    builder.StartObject(8)

def Start(builder):
    WeatherControlCommandStart(builder)

def WeatherControlCommandAddAmbientTemp(builder, ambientTemp):
    builder.PrependFloat64Slot(0, ambientTemp, 0.0)

def AddAmbientTemp(builder, ambientTemp):
    WeatherControlCommandAddAmbientTemp(builder, ambientTemp)

def WeatherControlCommandAddTrackTemp(builder, trackTemp):
    builder.PrependFloat64Slot(1, trackTemp, 0.0)

def AddTrackTemp(builder, trackTemp):
    WeatherControlCommandAddTrackTemp(builder, trackTemp)

def WeatherControlCommandAddDarkCloud(builder, darkCloud):
    builder.PrependFloat64Slot(2, darkCloud, 0.0)

def AddDarkCloud(builder, darkCloud):
    WeatherControlCommandAddDarkCloud(builder, darkCloud)

def WeatherControlCommandAddRaining(builder, raining):
    builder.PrependFloat64Slot(3, raining, 0.0)

def AddRaining(builder, raining):
    WeatherControlCommandAddRaining(builder, raining)

def WeatherControlCommandAddWindSpeed(builder, windSpeed):
    builder.PrependFloat64Slot(4, windSpeed, 0.0)

def AddWindSpeed(builder, windSpeed):
    WeatherControlCommandAddWindSpeed(builder, windSpeed)

def WeatherControlCommandAddWindDirection(builder, windDirection):
    builder.PrependFloat64Slot(5, windDirection, 0.0)

def AddWindDirection(builder, windDirection):
    WeatherControlCommandAddWindDirection(builder, windDirection)

def WeatherControlCommandAddMinPathWetness(builder, minPathWetness):
    builder.PrependFloat64Slot(6, minPathWetness, 0.0)

def AddMinPathWetness(builder, minPathWetness):
    WeatherControlCommandAddMinPathWetness(builder, minPathWetness)

def WeatherControlCommandAddMaxPathWetness(builder, maxPathWetness):
    builder.PrependFloat64Slot(7, maxPathWetness, 0.0)

def AddMaxPathWetness(builder, maxPathWetness):
    WeatherControlCommandAddMaxPathWetness(builder, maxPathWetness)

def WeatherControlCommandEnd(builder):
    return builder.EndObject()

def End(builder):
    return WeatherControlCommandEnd(builder)
